Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-11, with the labels that each got.

#1578 [2.11] Bump version to 2.11.8
  amis/packer_variables.json
  attributes/default.rb
  metadata.rb
Labels: skip-changelog-update, 2.x

#1579 [2.11] Revert "Backport update slurmctld and slurmd systemd service files"
  CHANGELOG.md
  files/default/slurmctld.service
  files/default/slurmd.service
Labels: skip-changelog-update, 2.x

#1582 [3.1.5] Backport nvidia driver update
  attributes/default.rb
Labels: skip-changelog-update

#1581 [MultiAZ] Include Networking/SubnetIds in the `fleet-config` file for CreateFleet API
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_fleet_config_generator.py
  test/unit/slurm/test_fleet_config_generator.py
  test/unit/slurm/test_fleet_config_generator/test_generate_fleet_config_file/expected_outputs/fleet-config.json
  test/unit/slurm/test_fleet_config_generator/test_generate_fleet_config_file/sample_input.yaml
Labels: enhancement, 3.x

#1584 [2.11] Upgrade EFA installer to `1.19.0`
  CHANGELOG.md
  attributes/default.rb
Labels: 2.x

#1585 [2.11] Backport Install efibootmgr before updating Ubuntu OS packages
  recipes/update_packages.rb
Labels: skip-changelog-update, 2.x

#1583 [3.1.x] Backport removal of gdr check
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1589 Prevent mountpoint collision between ephemeral drive and shared drives
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1591 [3.x] Upgrade EFA to 1.19.0
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1593 [3.1.x] Revert "Prevent mountpoint collision between ephemeral drive and shar…
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1592 [Versioning] Bump version to 3.4.0b1
  attributes/default.rb
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-install/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-test/metadata.rb
  metadata.rb
Labels: skip-changelog-update, 3.x

#1594 [surface head node bootstrap errors] rename error message file for both chef and custom scripts
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1599 [3.x] Add support for EFS in-transit encryption and iam authorization when updating clusters
  cookbooks/aws-parallelcluster-config/recipes/update_shared_storages.rb
  cookbooks/aws-parallelcluster-config/resources/manage_efs.rb
  cookbooks/aws-parallelcluster-config/templates/default/shared_storages/shared_storages_data.erb
Labels: skip-changelog-update

#1601 Remove python 3.6 check and fix ruby check
  .github/workflows/ci.yml
  tox.ini
Labels: skip-changelog-update

#1595 [surface head node bootstrap errors] store error messages from custom scripts
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1606 2.x: Use source_ami in place of source_ami_filter for CentOS7
  amis/packer_centos7.json
Labels: skip-changelog-update, 2.x

#1604 Fix system tests
  system_tests/install_cinc.sh
Labels: skip-changelog-update

#1607 [develop] Fix flake8 config
  .flake8
Labels: skip-changelog-update

#1610 Perform a describe stacks call only when a post install script has been provided
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
Labels: skip-changelog-update, 3.x

#1611 Log script that fails
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
Labels: skip-changelog-update, 3.x

#1612 Fix mount EFS File Systems with amazon-efs-utils
  cookbooks/aws-parallelcluster-config/resources/manage_efs.rb
Labels: skip-changelog-update
