Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-07, with the labels that each got.

#1474 [Licensing] Update copyright statement in NOTICE.txt
  NOTICE.txt
Labels: skip-changelog-update, 3.x

#1477 [Dependencies] Upgrade EFA installer to version 1.17.1
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1478 Review CHANGELOG for memory-based scheduling feature
  CHANGELOG.md
Labels: 3.x

#1471 Add Shellcheck to GitHub Action
  .github/workflows/ci.yml
  system_tests/install_cinc.sh
Labels: skip-changelog-update, 3.x

#1482 Prevent mountpoint collision between ephemeral drive and shared drives
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update, 3.x

#1484 [Versioning] Bump version to 3.2.0
  attributes/default.rb
Labels: skip-changelog-update, 3.x

#1487 Make disable_service and is_service_disabled more general setting platform_families default to the current value
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
Labels: skip-changelog-update

#1486 Add is_service_installed? helper to enable and run gdrcopy service only when the service is present
  cookbooks/aws-parallelcluster-config/libraries/helpers.rb
  cookbooks/aws-parallelcluster-config/recipes/nvidia.rb
Labels: skip-changelog-update

#1489 Fix is_service_installed? to search services also as init scripts
  cookbooks/aws-parallelcluster-config/libraries/helpers.rb
Labels: skip-changelog-update
