Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-05, with the labels that each got.

#1426 Fix gpg key nvidia fabricmanager in amazon linux 2 and centos 7
  attributes/default.rb
Labels: skip-changelog-update

#1427 2.x: Fix gpg key nvidia fabricmanager in amazon linux 2 and centos 7
  attributes/default.rb
Labels: skip-changelog-update, 2.x

#1428 cherry-pick: Fix gpg key nvidia fabricmanager in amazon linux 2 and centos 7
  attributes/default.rb
Labels: skip-changelog-update, 3.x

#1429 Add timeout of 300 seconds to execute command in cloudwatch_agent.rb recipe
  cookbooks/aws-parallelcluster-config/recipes/cloudwatch_agent.rb
Labels: skip-changelog-update

#1434 Bump cookbook to version 2.11.7
  amis/packer_variables.json
  attributes/default.rb
  metadata.rb
Labels: skip-changelog-update

#1433 Bump version to 3.1.4
  attributes/default.rb
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-install/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-test/metadata.rb
  metadata.rb
Labels: skip-changelog-update, 3.x

#1435 Update changelog of 3.1.4
  CHANGELOG.md
Labels: 3.x

#1437 Add changelog entries for 3.1.4
  CHANGELOG.md
Labels: 3.x

#1438 [develop] Avoid sending POWER_DOWN_ASAP to static node
  cookbooks/aws-parallelcluster-slurm/recipes/finalize_compute.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  libraries/helpers.rb
Labels: skip-changelog-update

#1440 [develop] Fix regex to match Slurm nodenames
  libraries/helpers.rb
Labels: skip-changelog-update

#1441 [develop] Simplify way to configure additional prolog/epilog scripts
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update

#1443 Fix gpg key nvidia fabricmanager for ubuntu 2004 and 1804
  attributes/default.rb
Labels: skip-changelog-update

#1445 Fix gpg key nvidia fabricmanager for ubuntu 2004 and 1804
  attributes/default.rb
Labels: skip-changelog-update
