Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-09, with the labels that each got.

#1513 3.x Upgrade Python from v3.7.10 to v3.7.13
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1515 Remove update_certificates.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/recipes/update_certificates.rb
Labels: skip-changelog-update, 3.x

#1517 Upgrade Python from v3.7.10 to v3.7.13 (#1513)
  CHANGELOG.md
  attributes/default.rb
Labels: dependencies, 3.x

#1516 [develop] Clean up cloud-init artifacts
  cookbooks/aws-parallelcluster-install/files/default/base/ami_cleanup.sh
Labels: skip-changelog-update

#1510 Refactor mount share storages recipes and create mount share storage resources
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/recipes/efs_mount.rb
  cookbooks/aws-parallelcluster-config/recipes/fs_mount.rb
  cookbooks/aws-parallelcluster-config/recipes/fsx_mount.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_base.rb
  cookbooks/aws-parallelcluster-config/resources/manage_ebs.rb
  cookbooks/aws-parallelcluster-config/resources/mount_efs.rb
  cookbooks/aws-parallelcluster-config/resources/mount_fsx.rb
Labels: skip-changelog-update, 3.x

#1526 Fix python version for cfn_bootstrap_virtualenv to 3.7.14 for a bug in aws-cfn-bootstrap-py3-latest.tar.gz
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/python.rb
Labels: skip-changelog-update

#1533 Fix NFS installation on Ubuntu
  cookbooks/aws-parallelcluster-install/recipes/base.rb
Labels: skip-changelog-update

#1498 [DFSM] Add DFSM support for ebs, efs and fsx
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/recipes/compute_base.rb
  cookbooks/aws-parallelcluster-config/recipes/fs_mount.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_base.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_raid.rb
  cookbooks/aws-parallelcluster-config/recipes/update.rb
  cookbooks/aws-parallelcluster-config/resources/manage_ebs.rb
  cookbooks/aws-parallelcluster-config/resources/manage_efs.rb
  cookbooks/aws-parallelcluster-config/resources/manage_fsx.rb
  cookbooks/aws-parallelcluster-config/templates/default/shared_storages/shared_storages_data.erb
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/manageVolume.py
  cookbooks/aws-parallelcluster-install/recipes/ec2_udev_rules.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_shared_storages.rb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1521 [DFSM] Add DFSM for Raid
  cookbooks/aws-parallelcluster-config/recipes/head_node_raid.rb
  cookbooks/aws-parallelcluster-config/resources/manage_raid.rb
  cookbooks/aws-parallelcluster-config/templates/default/shared_storages/shared_storages_data.erb
  cookbooks/aws-parallelcluster-slurm/recipes/update_shared_storages.rb
Labels: skip-changelog-update

#1532 3.x Add slurmdbd.log to CloudWatch logs
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_files.json
Labels: skip-changelog-update, 3.x

#1525 3.x Install MySql client packages
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/recipes/install_mysql_client.rb
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/recipes/validate_mysql.rb
  cookbooks/aws-parallelcluster-test/recipes/validations.rb
  recipes/validations.rb
Labels: skip-changelog-update, dependencies, 3.x

#1543 [EFA] Upgrade EFA from 1.17.2 to 1.18.0
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1530 Add support for Slurm Accounting
  CHANGELOG.md
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster.conf
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster_slurmdbd.conf
  cookbooks/aws-parallelcluster-slurm/recipes/clear_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/slurmdbd.service.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_slurm_database_password.sh.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurmdbd.conf.erb
  cookbooks/aws-parallelcluster-test/recipes/test_users.rb
  libraries/helpers.rb
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/sample_input_mem_sched.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster_slurm_accounting.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster_slurmdbd.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster_slurmdbd_slurm_accounting.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input_slurm_accounting.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_instance_types_data.json
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_input.yaml
Labels: 3.x

#1541 [Versioning] Bump version to 3.3.0b1
  attributes/default.rb
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-install/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-test/metadata.rb
  metadata.rb
Labels: skip-changelog-update, 3.x

#1523 backport support for rebooting compute nodes via Slurm
  templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update

#1544 Upgrade NICE DCV to version 2022.1-13300
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1546 Small changes for Slurm Accounting configurations
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurmdbd.conf.erb
  cookbooks/aws-parallelcluster-test/recipes/test_users.rb
  cookbooks/aws-parallelcluster-test/recipes/validate_mysql.rb
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/sample_input_mem_sched.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster_slurm_accounting.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster_slurmdbd_slurm_accounting.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input_slurm_accounting.yaml
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_input.yaml
Labels: skip-changelog-update

#1547 Fix hardcoded region in MySQL validation test
  attributes/default.rb
Labels: skip-changelog-update, 3.x
