Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-08, with the labels that each got.

#1495 [release-3.2] Add file to disable cron.weekly jobs
  cookbooks/aws-parallelcluster-install/files/default/cron/jobs.deny.daily
  cookbooks/aws-parallelcluster-install/files/default/cron/jobs.deny.weekly
  cookbooks/aws-parallelcluster-install/recipes/cron.rb
Labels: skip-changelog-update

#1496 [develop] Add file to disable cron.weekly jobs
  cookbooks/aws-parallelcluster-install/files/default/cron/jobs.deny.daily
  cookbooks/aws-parallelcluster-install/files/default/cron/jobs.deny.weekly
  cookbooks/aws-parallelcluster-install/recipes/cron.rb
Labels: skip-changelog-update

#1497 [develop] Remove manual disable hyperthreading recipe
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/files/default/disable_hyperthreading/disable_hyperthreading_manually.sh
  cookbooks/aws-parallelcluster-config/recipes/disable_hyperthreading.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  system_tests/dna.json
Labels: skip-changelog-update

#1499 [FIT] Support generation of slurm configuration files when using multi-instance type Compute Resources
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/common/slurm_parallelcluster_utils.conf
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster_queue_gres.conf
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster_queue_partition.conf
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/instance_name_type_mappings.json
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue1_gres.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue1_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue2_gres.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue2_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue3_gres.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue3_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/slurm_parallelcluster_cgroup.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/slurm_parallelcluster_gres.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_instance_types_data.json
Labels: 3.x

#1502 Add aws/aws-parallelcluster to codeowners
  .github/CODEOWNERS
Labels: skip-changelog-update

#1503 3.x [Dependencies] Upgrade Intel MPI to version 2021.6.0
  attributes/default.rb
Labels: skip-changelog-update, 3.x

#1501 3.2: [Dependencies] Upgrade Intel MPI to version 2021.6.0
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1505 Generate new configuration file to share compute resource info required to create fleet API
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_fleet_config_generator.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  test/unit/slurm/test_fleet_config_generator.py
  test/unit/slurm/test_fleet_config_generator/test_generate_fleet_config_file/expected_outputs/fleet-config.json
  test/unit/slurm/test_fleet_config_generator/test_generate_fleet_config_file/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator.py
Labels: skip-changelog-update

#1504 3.x Reduce the boot time DynamoDB invocation timeout from 10 minutes to 5 minutes
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/recipes/config_compute.rb
  cookbooks/aws-parallelcluster-slurm/recipes/finalize_compute.rb
  cookbooks/aws-parallelcluster-slurm/recipes/init.rb
  cookbooks/aws-parallelcluster-slurm/recipes/init_dns.rb
  libraries/helpers.rb
  util/upload-cookbook.sh
Labels: 3.x

#1506 Fix device_number to be set as an incremental counter
  CHANGELOG.md
  cookbooks/aws-parallelcluster-config/files/default/network_interfaces/configure_nw_interface.sh
  cookbooks/aws-parallelcluster-config/files/ubuntu/network_interfaces/configure_nw_interface.sh
  cookbooks/aws-parallelcluster-config/recipes/network_interfaces.rb
Labels: skip-changelog-update

#1511 Fix variable used for fleet config path
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update
