Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-06, with the labels that each got.

#1455 Add validator for MemoryInfo from EC2 API
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
Labels: skip-changelog-update, 3.x

#1457 Expose internal memory-based scheduling parameters as Chef parameters
  .gitignore
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_efa_partition_mem_sched.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_gpu_partition_mem_sched.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_multiple_spot_partition_mem_sched.conf
Labels: skip-changelog-update, 3.x

#1461 Change installation path of cfn-bootstrap
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/templates/default/base/parallelcluster_supervisord.conf.erb
  cookbooks/aws-parallelcluster-install/recipes/python.rb
  cookbooks/aws-parallelcluster-install/templates/default/base/pcluster.sh.erb
Labels: skip-changelog-update

#1465 [Dependencies] Upgrade EFA installer to version 1.16.0
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1466 [develop] Remove check on EFA GDR
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1467 [Versioning] Bump version to 3.2.0b2.
  attributes/default.rb
Labels: skip-changelog-update, 3.x

#1470 Use systemctl command to enable GDRCopy service on Ubuntu
  cookbooks/aws-parallelcluster-config/recipes/nvidia.rb
Labels: skip-changelog-update
