Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-10, with the labels that each got.

#1550 Fix Slurm Accounting password update script
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_slurm_database_password.sh.erb
Labels: skip-changelog-update, 3.x

#1551 Revert "[Dependencies] Downgrade Slurm to version 21.08.8"
  CHANGELOG.md
  attributes/default.rb
Labels: bug, 3.x

#1552 [develop] Fix Slurm config generation for instance type with GPU != Nvidia
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue8_gres.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue8_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/slurm_parallelcluster_gres.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_instance_types_data.json
Labels: skip-changelog-update

#1553 [Linter] Enable PyLint static code analysis
  .pylintrc
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_configs_util.py
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-config/files/default/dcv/pcluster_dcv_authenticator.py
  cookbooks/aws-parallelcluster-install/files/default/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/__init__.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_fleet_config_generator.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  test/unit/clusterstatusmgtd/test_clusterstatusmgtd.py
  test/unit/compute_fleet_status/test_compute_fleet_status.py
  test/unit/conftest.py
  test/unit/dcv/test_dcv_authenticator.py
  test/unit/slurm/test_fleet_config_generator.py
  test/unit/slurm/test_slurm_config_generator.py
  tox.ini
Labels: skip-changelog-update

#1558 [Test] Fix expected number of NFS threads in test
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update, 3.x

#1538 [Versioning] Bump version to 3.3.0
  attributes/default.rb
Labels: skip-changelog-update, 3.x

#1561 Increasing mounting retry_delay for EFS to 60 seconds
  cookbooks/aws-parallelcluster-config/resources/manage_efs.rb
Labels: skip-changelog-update

#1562 Fix pre-commit hooks config
  .pre-commit-config.yaml
Labels: skip-changelog-update

#1563 [DFSM] Move backing up shared storage data to fetch_config recipe
  cookbooks/aws-parallelcluster-config/recipes/update.rb
  cookbooks/aws-parallelcluster-config/resources/fetch_config.rb
  libraries/helpers.rb
Labels: skip-changelog-update

#1564 Fix efs mount error
  cookbooks/aws-parallelcluster-config/resources/manage_efs.rb
Labels: skip-changelog-update

#1567 [3.x] Install EFS-utils on Amazon Linux 2 AMI
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/efs.rb
Labels: skip-changelog-update

#1571 Backport remove rubocop-gitlab-security
  .rubocop.yml
Labels: skip-changelog-update

#1574 Remove validation of MySQL packages on Ubuntu 18.04/20.04 ARM as they are installed from OS repos.
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/install_mysql_client.rb
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/recipes/validate_mysql.rb
Labels: bug, skip-changelog-update, 3.x

#1575 Fix command used to validate MySQL client version in Ubuntu.
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
Labels: bug, skip-changelog-update, 3.x
