Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-01, with the labels that each got.

#1308 Revert DB initialization for the byos case
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/config_head_node.rb
Labels: skip-changelog-update

#1307 [develop] Add nvidia and cuda url for ARM case
  CHANGELOG.md
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/recipes/dcv.rb
  cookbooks/aws-parallelcluster-install/recipes/dcv.rb
  cookbooks/aws-parallelcluster-install/recipes/nvidia.rb
  libraries/helpers.rb
Labels: skip-changelog-update

#1312 3.1: Configure LDAP access filter in SSSD
  cookbooks/aws-parallelcluster-config/templates/default/directory_service/sssd.conf.erb
Labels: skip-changelog-update

#1309 Add checksum verification for scheduler plugin artifacts
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/fetch_artifacts.rb
Labels: skip-changelog-update

#1293 2.x: Upgrade to Intel MPI Library 2021.4.0.441
  CHANGELOG.md
  attributes/default.rb
  recipes/intel_mpi.rb
  templates/default/intel_mpi/qt_source_code.erb
Labels: 2.x

#1313 3.x: Upgrade to Intel MPI Library 2021.4.0.441
  CHANGELOG.md
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/intel_mpi.rb
  cookbooks/aws-parallelcluster-install/templates/default/intel_mpi/qt_source_code.erb
Labels: 3.x

#1305 [byos] Enable compute fleet status update for the byos case
  .kitchen.yml
  attributes/default.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_computemgtd.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_slurm_resume.conf.erb
  libraries/helpers.rb
  system_tests/dna.json
Labels: skip-changelog-update

#1319 [byos] Fix variable name for Slurm dynamoDB table
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
Labels: skip-changelog-update

#1310 Implement workaround for Slurm+OpenMPI when `add_node_hostnames_in_hosts_file`  is set to true
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_files.json
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/epilog
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/prolog
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update

#1324 3.x: Fix string used to verify Intel MPI installation on kitchen tests
  attributes/default.rb
Labels: skip-changelog-update, 3.x

#1325 2.x: Fix string used to verify Intel MPI installation on kitchen tests
  attributes/default.rb
Labels: skip-changelog-update, 2.x

#1327 [byos] Fix invoke handler script syntax for HeadComputeFleetUpdate
  cookbooks/aws-parallelcluster-scheduler-plugin/files/default/event_handler/invoke-scheduler-plugin-event-handler.sh
Labels: skip-changelog-update

#1330 [byos] Change permission for the scheduler-plugin python virtual env
  cookbooks/aws-parallelcluster-install/resources/install_pyenv.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/install_python.rb
Labels: skip-changelog-update

#1317 Add get-compute-fleet-status and update-compute-fleet-status script
  cookbooks/aws-parallelcluster-scheduler-plugin/files/default/compute_fleet_status/compute_fleet_status.py
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/templates/default/compute_fleet_status/get-compute-fleet-status.erb
  cookbooks/aws-parallelcluster-scheduler-plugin/templates/default/compute_fleet_status/update-compute-fleet-status.erb
  test/unit/compute_fleet_status/test_compute_fleet_status.py
  tox.ini
Labels: skip-changelog-update

#1322 Improve imds access configuration
  cookbooks/aws-parallelcluster-config/recipes/imds.rb
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/recipes/test_imds.rb
Labels: skip-changelog-update

#1333 [byos] Convert time format for lastStatusUpdateTime
  cookbooks/aws-parallelcluster-scheduler-plugin/files/default/compute_fleet_status/compute_fleet_status.py
  test/unit/compute_fleet_status/test_compute_fleet_status.py
Labels: skip-changelog-update

#1334 [byos] Add clusterstatusmgtd log to CloudWatch
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_files.json
Labels: skip-changelog-update

#1329 Signal CloudFormation with an explicit error message
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/execute_event_handler.rb
  libraries/helpers.rb
Labels: skip-changelog-update

#1337 Do not check parallelcluster-iptables service on awsbatch clusters
  cookbooks/aws-parallelcluster-test/recipes/test_imds.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1335 Install DCV web viewer
  CHANGELOG.md
  attributes/default.rb
  recipes/dcv_install.rb
Labels: 2.x

#1341 [byos] Merge from develop + version bump
  attributes/default.rb
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-install/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-test/metadata.rb
  metadata.rb
Labels: skip-changelog-update

#1343 Enable slurm_nss plugin
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_compute.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update

#1340 Rename web-viewer to web_viewer
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/dcv.rb
Labels: skip-changelog-update, 3.x
