Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-02, with the labels that each got.

#1344 Fix check_sudoers_permissions kitchen test
  cookbooks/aws-parallelcluster-test/recipes/test_users.rb
Labels: skip-changelog-update

#1348 [byos] add slurm_fleet_status_manager log to cloudwatch
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_files.json
Labels: skip-changelog-update

#1349 Force file override when copying plugin configurations
  cookbooks/aws-parallelcluster-config/resources/fetch_config.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/execute_event_handler.rb
Labels: skip-changelog-update

#1354 [byos] Add clusterstatusmgtd log to CW for slurm case
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_files.json
Labels: skip-changelog-update

#1346 Do not grant system users sudo privileges in case GrantSudoPrivileges is set to false
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/init_user.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/create_user.rb
Labels: skip-changelog-update

#1357 2.x: Remove check to verify Intel MPI rpm is installed
  recipes/tests.rb
Labels: skip-changelog-update, 2.x

#1356 Add nss_slurm.conf in compute nodes when nss plugin is used
  cookbooks/aws-parallelcluster-slurm/recipes/config_compute.rb
Labels: skip-changelog-update

#1359 Use YAML.safe_load when reading cluster config
  libraries/helpers.rb
Labels: skip-changelog-update

#1347 [develop] Increase retries for gcc sources download
  cookbooks/aws-parallelcluster-install/recipes/arm_pl.rb
Labels: skip-changelog-update

#1360 [byos] Avoid privilege escalation via symbolic links
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/execute_event_handler.rb
Labels: skip-changelog-update

#1362 [develop] Add option to skip plugin artifacts download
  cookbooks/aws-parallelcluster-scheduler-plugin/files/default/event_handler/invoke-scheduler-plugin-event-handler.sh
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/invoke_scheduler_plugin_event_handler.rb
Labels: skip-changelog-update

#1364 Bump version to 3.2.0
  attributes/default.rb
Labels: skip-changelog-update

#1366 [develop] Mock cluster stack arn for kitchen test run
  cookbooks/aws-parallelcluster-test/recipes/tests_mock.rb
Labels: skip-changelog-update

#1367 [develop] Add cluster config path override for kitchen test
  .kitchen.yml
Labels: skip-changelog-update

#1368 [develop] Add mocks for config files required in compute
  .kitchen.yml
  cookbooks/aws-parallelcluster-test/recipes/tests_mock.rb
Labels: skip-changelog-update

#1369 [develop] Fix format for dummy compute fleet status
  cookbooks/aws-parallelcluster-scheduler-plugin/files/default/event_handler/invoke-scheduler-plugin-event-handler.sh
Labels: skip-changelog-update

#1371 2.x: Move Intel MPI change in the right version
  CHANGELOG.md
Labels: 2.x

#1374 Bump version to 2.11.5
  amis/packer_variables.json
  attributes/default.rb
  metadata.rb
Labels: skip-changelog-update

#1355 Configurable slurm nodes bootstrap timeout
  attributes/default.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/execute_event_handler.rb
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster.conf
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
  system_tests/dna.json
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files/expected_outputs/slurm_parallelcluster.conf
Labels: skip-changelog-update

#1370 Add kitchen test for scheduler plugin
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1379 2.x: Add force to mkfs.ext4 in encrypted ephemeral
  files/default/setup-ephemeral-drives.sh
Labels: skip-changelog-update, 2.x

#1380 Change log file permission
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/init.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
Labels: skip-changelog-update
