Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-04, with the labels that each got.

#1410 Add dkms nvidia override with AL2-kernel5
  cookbooks/aws-parallelcluster-install/files/amazon/dkms/nvidia.conf
  cookbooks/aws-parallelcluster-install/recipes/nvidia.rb
Labels: skip-changelog-update

#1411 Add package to build Nvidia driver on AL2 Kernel 5
  cookbooks/aws-parallelcluster-install/recipes/nvidia.rb
Labels: skip-changelog-update

#1409 3.x: Restart clustermgtd and slurmctld only when queue parameters update
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  libraries/helpers.rb
Labels: 3.x

#1408 3.x: Set AuthInfo=cred_expire=70
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: 3.x

#1420 Set default insufficient_capacity_timeout = 600
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
Labels: skip-changelog-update, 3.x

#1424 Add new line in the parallelcluster_clustermgtd.conf
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
Labels: skip-changelog-update, 3.x
