Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2022-12, with the labels that each got.

#1616 Check that IMDS for IPv6 is enabled before testing IMDS access for specific users
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1620 [Versioning] Bump version to 3.4.0
  attributes/default.rb
Labels: skip-changelog-update

#1624 Reintroduce sleep between slurmctld restart and reconfigure
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update, 3.x

#1626 Add check to prevent security exclusions in code
  .github/workflows/security_exclusions_checker.yml
Labels: skip-changelog-update

#1627 Add check to prevent security exclusions in code
  .github/workflows/security_exclusions_checker.yml
Labels: skip-changelog-update

#1623 [3.x] Update Stunnel Url
  attributes/default.rb
Labels: skip-changelog-update

#1628 [3.4] Backport Update Stunnel Url #1623
  attributes/default.rb
Labels: skip-changelog-update

#1629 [Versioning] Bump ParallelCluster AWSBatch CLI version to 1.1.0
  attributes/default.rb
Labels: skip-changelog-update

#1630 Upgrade Slurm to version 22.05.7
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1631 Upgrade Slurm to version 22.05.7
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x
