Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-08, with the labels that each got.

#2389 Set --no-cc-version-check flag to build on ubuntu 22.04
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
Labels: skip-changelog-update

#2391 Move the NFS config file override from the setup action to configure via override_server_template
  cookbooks/aws-parallelcluster-environment/resources/nfs/nfs_ubuntu22+.rb
Labels: skip-changelog-update

#2393 Move ulimit check to install phase and switch user to reflect changes to the config
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/test/controls/users_spec.rb
Labels: skip-changelog-update

#2394 Move ulimit check to install phase and switch user to reflect changes…
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/test/controls/users_spec.rb
Labels: skip-changelog-update

#2397 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog-update, skip-system-tests

#2398 Upgrade slurm to version 23.02.4
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: 3.x

#2399 Upgrade slurm to version 23.02.4
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: 3.x

#2400 [Release-3.7] Move ulimit check back to config since it fails on jenkins
  cookbooks/aws-parallelcluster-platform/test/controls/users_spec.rb
Labels: skip-changelog-update

#2401 Move ulimit check back to config since it fails on jenkins
  cookbooks/aws-parallelcluster-platform/test/controls/users_spec.rb
Labels: skip-changelog-update

#2403 [Release 3.7] update the volume size default to 40 to address issues with Centos 7 …
  kitchen.ec2.yml
Labels: skip-changelog-update

#2402 update the volume size default to 40 to address issues with Centos 7 …
  kitchen.ec2.yml
Labels: skip-changelog-update

#2404 Set --no-cc-version-check flag to build on ubuntu 22.04 (#2389)
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
Labels: skip-changelog-update

#2406 [Release 3.7] Add ubuntu 22.04 to dcv connect script and mysql client…
  cookbooks/aws-parallelcluster-platform/files/dcv/pcluster_dcv_connect.sh
  cookbooks/aws-parallelcluster-slurm/test/controls/mysql_client_spec.rb
Labels: skip-changelog-update

#2407 Add ubuntu 22.04 to dcv connect script and mysql client install check
  cookbooks/aws-parallelcluster-platform/files/dcv/pcluster_dcv_connect.sh
  cookbooks/aws-parallelcluster-slurm/test/controls/mysql_client_spec.rb
Labels: skip-changelog-update

#2409 [Fault Tolerance] Add retry with delay to the block to copy Munge key and the blocks to start Chronyd and Munge services.
  cookbooks/aws-parallelcluster-platform/resources/chrony/partial/_chrony_common.rb
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#2410 [Fault Tolerance] Add retry with delay to the block to copy Munge key and the blocks to start Chronyd and Munge services.
  cookbooks/aws-parallelcluster-platform/resources/chrony/partial/_chrony_common.rb
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#2388 Update the NVIDIA Drivers for P5 instance
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/nvidia_driver_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/cuda_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
Labels: 3.x

#2412 [release-3.7] Upgrading NVIDIA driver,fabric manager and Cuda to v535 and v12.2 res…
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/nvidia_driver_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/cuda_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
Labels: 3.x

#2423 [release-3.7] Generate RSA Host key for alinux2 platforms
  cookbooks/aws-parallelcluster-environment/files/login_nodes/keys-manager.sh
  cookbooks/aws-parallelcluster-environment/test/controls/login_nodes_keys_spec.rb
Labels: skip-changelog-update, 3.x

#2422 [develop] Generate RSA Host keys for alinux2 platform
  cookbooks/aws-parallelcluster-environment/files/login_nodes/keys-manager.sh
  cookbooks/aws-parallelcluster-environment/test/controls/login_nodes_keys_spec.rb
Labels: skip-changelog-update, 3.x

#2424 Bump version to 3.7.0
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  kitchen.ec2.yml
Labels: skip-changelog-update

#2427 [develop] Skip ephemeral drives mount check for custom AMIs (e.g. DLAMI)
  cookbooks/aws-parallelcluster-environment/test/controls/ephemeral_drives_spec.rb
Labels: skip-changelog-update

#2428 Move Spack resource to environment cookbook
  cookbooks/aws-parallelcluster-environment/files/spack/modules.yaml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/recipes/install.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/partial/_spack_common.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/spack_amazon2.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/spack_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/spack_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/spack_ubuntu20.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/spack_ubuntu22.rb
  cookbooks/aws-parallelcluster-environment/templates/spack/packages-aarch64.yaml.erb
  cookbooks/aws-parallelcluster-environment/templates/spack/packages-icelake.yaml.erb
  cookbooks/aws-parallelcluster-environment/templates/spack/packages-neoverse_n1.yaml.erb
  cookbooks/aws-parallelcluster-environment/templates/spack/packages-skylake_avx512.yaml.erb
  cookbooks/aws-parallelcluster-environment/templates/spack/packages-zen2.yaml.erb
  cookbooks/aws-parallelcluster-environment/templates/spack/spack.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/spack_spec.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/recipes/install.rb
Labels: skip-changelog-update

#2431 [release-3.7] Add NVSwitch Device Id for P5 instance
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_common.rb
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
Labels: skip-changelog-update, 3.x

#2433 Add NVSwitch Device Id for P5 instance
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_common.rb
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
Labels: skip-changelog-update, 3.x

#2434 [develop] Update cinc-install.sh file to latest version
  util/cinc-install.sh
Labels: skip-changelog-update

#2435 [Tests]Configure Fabric Manager and nvidia persistence for running Sanity Checks
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
Labels: skip-changelog-update, 3.x

#2439 [develop] Remove useless pre_verify step to fix inspec file path
  README.md
  kitchen.validate-config.yml
  kitchen/kitchen.fix-inspec-deps.sh
Labels: skip-changelog-update
