Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-04, with the labels that each got.

#1974 [develop] Add logic to retrieve custom slurm settings file from S3
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/retrieve_remote_custom_settings_file.rb
  cookbooks/aws-parallelcluster-slurm/resources/remote_object/remote_object.rb
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/retrieve_remote_custom_settings_file_spec.rb
Labels: skip-changelog-update, 3.x

#1976 3.x Remove lazy evaluation and conditional include
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/retrieve_remote_custom_settings_file.rb
Labels: skip-changelog-update, 3.x

#1978 Fix cookstyle offenses
  cookbooks/aws-parallelcluster-config/recipes/cloudwatch_agent.rb
  cookbooks/aws-parallelcluster-config/recipes/custom_actions_setup.rb
  cookbooks/aws-parallelcluster-config/recipes/directory_service.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_fleet_status.rb
  cookbooks/aws-parallelcluster-config/recipes/intel.rb
  cookbooks/aws-parallelcluster-install/recipes/arm_pl.rb
  cookbooks/aws-parallelcluster-install/recipes/cloudwatch_agent.rb
  cookbooks/aws-parallelcluster-install/recipes/dcv.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/partial/_setup.rb
Labels: skip-changelog-update

#1980 [3.x] Enable nvidia config recipe and tests on redhat8
  cookbooks/aws-parallelcluster-common/test/common/libraries/instance.rb
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_config/nvidia_spec.rb
Labels: skip-changelog-update

#1983 [develop]Fix import of custom slurm settings file recipe
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
Labels: skip-changelog-update, 3.x

#1987 Enable oddjobd daemon as part of rhel8 Active directory configuration
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_redhat8.rb
  kitchen.resources-config.yml
  test/resources/controls/aws_parallelcluster_config/system_authentication_spec.rb
Labels: skip-changelog-update

#1988 Remove gdrcopy service from InSpec test since duplicate
  test/resources/controls/aws_parallelcluster_install/nvidia_spec.rb
Labels: skip-changelog-update

#1981 3.x Use cluster_name property for cluster name
  cookbooks/aws-parallelcluster-config/files/default/custom_action_executor/custom_action_executor.py
  cookbooks/aws-parallelcluster-config/recipes/custom_actions_setup.rb
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  cookbooks/aws-parallelcluster-slurm/libraries/emit_chef_error_event.rb
  test/unit/custom_action_executor/test_custom_action_executor.py
Labels: skip-changelog-update, 3.x

#1992 Modify comment in slurm_parallelcluster.conf
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/slurm_parallelcluster_mem_sched.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/expected_outputs/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/expected_outputs/slurm_parallelcluster_slurm_accounting.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/slurm_parallelcluster.conf
Labels: skip-changelog-update, 3.x

#1993 Refactor recipe cloudwatch_agent config into a resource action
  cookbooks/aws-parallelcluster-common/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch/cloudwatch_agent_config_schema.json
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch/cloudwatch_agent_config_util.py
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-config/recipes/cloudwatch_agent.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-config/recipes/test_resource.rb
  cookbooks/aws-parallelcluster-test/recipes/docker_mock.rb
  kitchen.recipes-config.yml
  kitchen.resources-config.yml
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_config/cloudwatch_spec.rb
  tox.ini
Labels: skip-changelog-update

#1990 fetch_and_run source /etc/parallelcluster/cfnconfig in a backward compatible way
  cookbooks/aws-parallelcluster-config/files/default/custom_action_executor/custom_action_executor.py
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  test/unit/custom_action_executor/test_custom_action_executor.py
Labels: enhancement, skip-changelog-update, 3.x

#1996 [develop] Fix condition for custom settings file override
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/retrieve_remote_custom_settings_file.rb
  cookbooks/aws-parallelcluster-slurm/resources/remote_object/remote_object.rb
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/retrieve_remote_custom_settings_file_spec.rb
Labels: skip-changelog-update, 3.x

#1995 [Fix] Make supervisord manage the cfn-hup program in no-daemon mode
  CHANGELOG.md
  cookbooks/aws-parallelcluster-config/templates/default/base/parallelcluster_supervisord.conf.erb
  cookbooks/aws-parallelcluster-install/recipes/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-install/templates/default/base/cfn-hup-runner.sh.erb
Labels: bug, 3.x

#1997 Upgrade Slurm to version 23.02.1 and munge to version 0.5.15
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: 3.x

#2004 Fix cloudwatch_spec check for file cloudwatch_agent_config.json
  test/resources/controls/aws_parallelcluster_config/cloudwatch_spec.rb
Labels: skip-changelog-update

#2005 [develop] Add logic to retrieve custom slurms settings file in update recipe
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update, 3.x

#2003 Fix spelling error in fetch_and_run parameter
  cookbooks/aws-parallelcluster-config/recipes/custom_actions_setup.rb
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
Labels: skip-changelog-update, 3.x

#2010 Set kitchen-transport-speedy as transport for ec2 kitchen
  Gemfile
  README.md
  kitchen.ec2.yml
Labels: skip-changelog-update

#2008 [develop] Change default TreeWidth value
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: 3.x

#2006 Fix Slurm accounting password being overridden at queue update
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: 3.x

#2014 Add Changelog entry about building Slurm with support for LUA
  CHANGELOG.md
Labels: 3.x

#2013 Add resource for dcv install, with rhel8 support
  attributes/default.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/partial/_debian_common.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/partial/_rhel_common.rb
  cookbooks/aws-parallelcluster-install/files/default/dcv/pcluster_dcv_connect.sh
  cookbooks/aws-parallelcluster-install/recipes/dcv.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_install/dcv_spec.rb
Labels: skip-changelog-update, 3.x

#2015 Fix logic to reset Slurm accounting password after queue update
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update, 3.x

#2016 Support DCV config
  attributes/default.rb
  cookbooks/aws-parallelcluster-common/files/default/dcv/10_org.gnome.desktop.screensaver.gschema.override
  cookbooks/aws-parallelcluster-common/files/default/dcv/__init__.py
  cookbooks/aws-parallelcluster-common/files/default/dcv/generate_certificate.sh
  cookbooks/aws-parallelcluster-common/files/default/dcv/pcluster_dcv_authenticator.py
  cookbooks/aws-parallelcluster-common/files/default/dcv/pcluster_dcv_connect.sh
  cookbooks/aws-parallelcluster-common/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/partial/_debian_common.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/partial/_rhel_common.rb
  cookbooks/aws-parallelcluster-config/recipes/dcv.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_base.rb
  kitchen.resources-config.yml
  test/resources/controls/aws_parallelcluster_config/dcv_spec.rb
  tox.ini
Labels: skip-changelog-update, 3.x

#2019 fix formatting
  kitchen.resources-config.yml
Labels: skip-changelog-update

#2018 [develop] Moves the fix to renew the accounting credentials below in the recipe
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update, 3.x

#2020 3.x Fix date format to match CWA configuration
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/health_checks/gpu_health_check.sh
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/health_check/90_pcluster_health_check_manager.erb
Labels: skip-changelog-update, 3.x

#2022 Fix comment in find_os_minor_version
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_redhat8.rb
Labels: skip-changelog-update

#2026 Clean arm_pl resource and test
  cookbooks/aws-parallelcluster-install/attributes/default.rb
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  test/resources/controls/aws_parallelcluster_install/arm_pl_spec.rb
Labels: skip-changelog-update

#2024 Revert "remove lustre client installation for kernel 4.18.0-425.3.1.el8"
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_redhat8.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_setup_spec.rb
Labels: skip-changelog-update

#2028 Add explanation of how to avoid unknown locale error when running the tests
  README.md
Labels: skip-changelog-update

#2032 Lock fabricmanager version in rhel8
  cookbooks/aws-parallelcluster-common/resources/fabric_manager/fabric_manager_redhat8.rb
  test/resources/controls/aws_parallelcluster_install/nvidia_spec.rb
Labels: skip-changelog-update, 3.x

#2021 3.x Add publishing of GPU failure metrics
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/event_utils.py
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/health_check_manager.py
  cookbooks/aws-parallelcluster-slurm/recipes/config_health_check.rb
  cookbooks/aws-parallelcluster-slurm/recipes/init.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/compute/slurm_node_spec.json.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/health_check/90_pcluster_health_check_manager.erb
  test/unit/health_check/test_event_utils.py
  test/unit/health_check/test_health_check_manager.py
Labels: skip-changelog-update, 3.x

#2035 Remove dependency on install_packages from arm_pl
  cookbooks/aws-parallelcluster-install/resources/arm_pl/partial/_arm_pl_common.rb
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_install/arm_pl_spec.rb
Labels: skip-changelog-update, 3.x

#2043 Transform node_attributes into a resource
  cookbooks/aws-parallelcluster-common/resources/node_attributes.rb
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/node_attributes_spec.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/resources/arm_pl/partial/_arm_pl_common.rb
  kitchen.recipes-install.yml
  kitchen.resources-config.yml
  kitchen.resources-install.yml
Labels: skip-changelog-update, 3.x
