Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-06, with the labels that each got.

#2241 Move directory_service.rb to environment cookbook
  cookbooks/aws-parallelcluster-config/libraries/helpers.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-config/recipes/update.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/directory_service.rb
  cookbooks/aws-parallelcluster-environment/templates/directory_service/generate_ssh_key.sh.erb
  cookbooks/aws-parallelcluster-environment/templates/directory_service/sssd.conf.erb
  cookbooks/aws-parallelcluster-environment/templates/directory_service/update_directory_service_password.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/directory_service_spec.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update, skip-system-tests

#2242 Restore previous condition on systemd checks
  test/recipes/controls/other_spec.rb
Labels: skip-changelog-update, skip-system-tests

#2246 [develop] Do not use DCV file exist to verify if DCV is configured or not
  cookbooks/aws-parallelcluster-config/recipes/log_rotation.rb
  cookbooks/aws-parallelcluster-config/recipes/sudo.rb
  cookbooks/aws-parallelcluster-config/spec/unit/recipes/sudo_config_spec.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_dcv_common.rb
Labels: skip-changelog-update

#2247 [develop] Move clusterstatusmgtd_init_slurm.rb to computefleet cookbook
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-computefleet/attributes/computefleet.rb
  cookbooks/aws-parallelcluster-computefleet/files/compute_fleet_status/compute_fleet_status.py
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-config.yml
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-install.yml
  cookbooks/aws-parallelcluster-computefleet/recipes/config/clusterstatusmgtd_config.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/config/head_node_fleet_status.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/install.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/install/clusterstatusmgtd_install.rb
  cookbooks/aws-parallelcluster-computefleet/spec/unit/recipes/clusterstatusmgtd_config_spec.rb
  cookbooks/aws-parallelcluster-computefleet/spec/unit/recipes/clusterstatusmgtd_install_spec.rb
  cookbooks/aws-parallelcluster-computefleet/templates/clusterstatusmgtd/99-parallelcluster-clusterstatusmgtd.erb
  cookbooks/aws-parallelcluster-computefleet/templates/clusterstatusmgtd/clusterstatusmgtd.conf.erb
  cookbooks/aws-parallelcluster-computefleet/templates/compute_fleet_status/get-compute-fleet-status.erb
  cookbooks/aws-parallelcluster-computefleet/templates/compute_fleet_status/update-compute-fleet-status.erb
  cookbooks/aws-parallelcluster-computefleet/test/controls/clusterstatusmgtd_spec.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_base.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-slurm/Berksfile
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_config/clusterstatusmgtd_init_slurm_spec.rb
  tox.ini
Labels: skip-changelog-update

#2249 Define node['cluster']['etc_dir'] attribute
  cookbooks/aws-parallelcluster-computefleet/recipes/config/head_node_fleet_status.rb
  cookbooks/aws-parallelcluster-config/attributes/default.rb
  cookbooks/aws-parallelcluster-config/recipes/cfnconfig_mixed.rb
  cookbooks/aws-parallelcluster-config/recipes/imds.rb
  cookbooks/aws-parallelcluster-config/recipes/sudo.rb
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/directories.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/directories_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-shared/attributes/cluster.rb
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update

#2251 [develop] Move fs_update recipe to environment
  cookbooks/aws-parallelcluster-config/attributes/default.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_base.rb
  cookbooks/aws-parallelcluster-config/recipes/update.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/fs_update.rb
  cookbooks/aws-parallelcluster-environment/templates/shared_storages/shared_storages_data.erb
  cookbooks/aws-parallelcluster-environment/test/controls/fs_update_spec.rb
  cookbooks/aws-parallelcluster-shared/attributes/cluster.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update

#2252 [develop] Remove load_shared_storages_mapping function
  cookbooks/aws-parallelcluster-config/libraries/helpers.rb
  cookbooks/aws-parallelcluster-config/recipes/update_shared_storages.rb
Labels: skip-changelog-update

#2250 Add Manage EBS kitchen tests to cover the manage_ebs resource
  cookbooks/aws-parallelcluster-config/resources/manage_ebs.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/resources/manage_ebs.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
  cookbooks/aws-parallelcluster-environment/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/manage_ebs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/volume_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/ebs_spec.rb
  cookbooks/aws-parallelcluster-tests/resources/test_resource.rb
  kitchen.ec2.sh
  kitchen.ec2.yml
  libraries/helpers.rb
Labels: skip-changelog-update

#2248 [develop] Move imds recipe to environment cookbook
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/files/imds/imds-access.sh
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/imds.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/imds_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/imds/parallelcluster-iptables.erb
  cookbooks/aws-parallelcluster-environment/test/controls/imds_spec.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update, skip-system-tests

#2260 Fix commented lines in manage_ebs resource - prepare_device method
  cookbooks/aws-parallelcluster-environment/resources/manage_ebs.rb
Labels: skip-changelog-update

#2198 Move cfnconfig_mixed to environment cookbook
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/attributes/default.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/recipes/install/cfnconfig_mixed.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfnconfig_mixed_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/init/cfnconfig.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cfnconfig_mixed_spec.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update

#2234 Add an exception message mapping and write exception message to the error file
  cookbooks/aws-parallelcluster-config/libraries/write_chef_error_handler.rb
Labels: skip-changelog-update, 3.x

#2262 [develop] Fix dcv_configured condition usage
  cookbooks/aws-parallelcluster-common/test/common/libraries/instance.rb
  cookbooks/aws-parallelcluster-config/recipes/log_rotation.rb
  cookbooks/aws-parallelcluster-config/recipes/sudo.rb
  cookbooks/aws-parallelcluster-config/spec/unit/recipes/sudo_config_spec.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/dcv_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/environment.rb
Labels: skip-changelog-update

#2264 Move fs_mount to environment cookbook.
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-environment/recipes/config/fs_mount.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/fs_mount_spec.rb
Labels: skip-changelog-update

#2265 Correcting the source path of cfnconfig.erb from config to environment cookbook
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/update_head_node_spec.rb
Labels: skip-changelog-update

#2266 Introduce a new approach to share info from lifecycle hooks to kitchen environment
  README.md
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/test/hooks/install/ebs_mount/post_create.sh
  cookbooks/aws-parallelcluster-environment/test/hooks/install/ebs_mount/pre_destroy.sh
  cookbooks/aws-parallelcluster-tests/resources/test_resource.rb
  kitchen.global.yml
  test/environments/kitchen.rb
Labels: skip-changelog-update

#2267 Move sudo recipe from config to platform cookbook
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/recipes/config/sudo_config.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/sudo_config_spec.rb
  cookbooks/aws-parallelcluster-platform/templates/base/99-parallelcluster-user-tty.erb
  cookbooks/aws-parallelcluster-platform/templates/base/parallelcluster_supervisord.conf.erb
  cookbooks/aws-parallelcluster-platform/test/controls/sudo_config_spec.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update

#2271 Move fetch_config resource to platform cookbook
  cookbooks/aws-parallelcluster-common/libraries/cluster_config.rb
  cookbooks/aws-parallelcluster-platform/resources/fetch_config.rb
  cookbooks/aws-parallelcluster-platform/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fetch_config_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/helpers.rb
Labels: skip-changelog-update

#2273 Supporting ubuntu22 for cloudwatch
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2280 Move log_rotation to platform cookbook
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/recipes/config.rb
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/recipes/config/log_rotation.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/log_rotation_spec.rb
  cookbooks/aws-parallelcluster-platform/templates/log_rotation/parallelcluster_log_rotation.erb
Labels: skip-changelog-update

#2275 Add support for FSX on Ubuntu 22
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb
  cookbooks/aws-parallelcluster-tests/resources/test_resource.rb
  test/environments/kitchen.rb
Labels: skip-changelog-update, skip-system-tests

#2281 Move enable_chef_error_handler to platform cookbook
  cookbooks/aws-parallelcluster-config/recipes/config.rb
  cookbooks/aws-parallelcluster-config/recipes/finalize.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-platform/recipes/config/enable_chef_error_handler.rb
  cookbooks/aws-parallelcluster-slurm/recipes/enable_chef_error_handler.rb
Labels: skip-changelog-update, skip-system-tests

#2283 Fix dcv condition used in Inspec Tests
  test/recipes/controls/other_spec.rb
Labels: skip-changelog-update, skip-system-tests

#2282 Move update_computefleet_status to computefleet cookbook
  cookbooks/aws-parallelcluster-computefleet/files/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-computefleet/recipes/config/update_computefleet_status.rb
  cookbooks/aws-parallelcluster-computefleet/templates/clusterstatusmgtd/99-parallelcluster-clusterstatusmgtd.erb
  cookbooks/aws-parallelcluster-entrypoints/recipes/update_computefleet_status.rb
  test/unit/clusterstatusmgtd/test_clusterstatusmgtd.py
Labels: skip-changelog-update, skip-system-tests

#2285 Move update_shared_storages.rb to environment
  cookbooks/aws-parallelcluster-environment/recipes/config/update_shared_storages.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update

#2274 Move Mount_shared recipe to environment cookbook
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/mount_shared.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/mount_shared_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/mount_shared_spec.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update

#2288 Correcting the cookbook for mount_shared recipe
  cookbooks/aws-parallelcluster-config/recipes/init.rb
Labels: skip-changelog-update

#2289 Use os_type resource for validation
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  libraries/helpers.rb
Labels: skip-changelog-update

#2295 Fix shared Inspec profile structure
  cookbooks/aws-parallelcluster-awsbatch/test/inspec.yml
  cookbooks/aws-parallelcluster-computefleet/test/inspec.yml
  cookbooks/aws-parallelcluster-entrypoints/test/inspec.yml
  cookbooks/aws-parallelcluster-environment/test/inspec.yml
  cookbooks/aws-parallelcluster-platform/test/inspec.yml
  cookbooks/aws-parallelcluster-shared/test/inspec.yml
  cookbooks/aws-parallelcluster-shared/test/libraries/instance.rb
  cookbooks/aws-parallelcluster-shared/test/libraries/node.rb
  cookbooks/aws-parallelcluster-shared/test/libraries/os_properties.rb
  cookbooks/aws-parallelcluster-slurm/test/inspec.yml
  kitchen.fix-inspec-deps.sh
  test/recipes/inspec.yml
Labels: skip-changelog-update

#2301 Execute fetch_config after the mount of shared folders
  cookbooks/aws-parallelcluster-entrypoints/recipes/init.rb
Labels: skip-changelog-update, skip-system-tests

#2302 Remove remaining cookbook related files from root folder
  Berksfile
  metadata.rb
  recipes/config.rb
  recipes/default.rb
  recipes/finalize.rb
  recipes/init.rb
  recipes/invoke_scheduler_plugin_event_handler.rb
  recipes/update.rb
Labels: skip-changelog-update

#2304 Execute inspec tests accordingly to node type and scheduler
  cookbooks/aws-parallelcluster-computefleet/test/controls/fleet_status_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/awscli_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/config_slurmd_systemd_service_spec.rb
Labels: skip-changelog-update, skip-system-tests

#2291 Update the ptrace_scope if clause to check the correct string and add a check in the kitchen test for the config file chef generates
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/resources/efa/partial/_disable_ptrace_debian.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/efa_spec.rb
Labels: skip-system-tests

#2303 Fix volume mount
  cookbooks/aws-parallelcluster-environment/recipes/config/ebs.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/ebs_spec.rb
Labels: skip-changelog-update, skip-system-tests

#2307 Explain code structure in the README file
  README.md
Labels: skip-changelog-update

#2308 Skip mount_shared recipe tests on head node
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/test/controls/mount_shared_spec.rb
Labels: skip-changelog-update

#2299 Remove scheduler-plugin code
  Berksfile
  cookbooks/aws-parallelcluster-computefleet/recipes/config/update_computefleet_status.rb
  cookbooks/aws-parallelcluster-entrypoints/Berksfile
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/config.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/finalize.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/init.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/install.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/update.rb
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config_schema.json
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-environment/templates/custom_actions/fetch_and_run.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/attributes/scheduler-plugin.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/files/default/event_handler/invoke-scheduler-plugin-event-handler.sh
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/config.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/config_compute.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/finalize.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/finalize_compute.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/finalize_head_node.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/init.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/init_compute.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/init_head_node.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/init_user.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/install.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/install_python.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/install_user.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/invoke_scheduler_plugin_event_handler.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/test/tests_mock.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/update.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/update_computefleet_status.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/update_computefleet_status_head_node.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/create_user.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/execute_event_handler.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/fetch_artifacts.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/set_user_privileges.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/templates/default/scheduler_plugin_user/99-parallelcluster-scheduler-plugin-sudoer-configuration.erb
  cookbooks/aws-parallelcluster-scheduler-plugin/templates/default/scheduler_plugin_user/99-parallelcluster-scheduler-plugin.erb
  cookbooks/aws-parallelcluster-shared/attributes/cluster.rb
  cookbooks/aws-parallelcluster-shared/attributes/users.rb
  metadata.rb
  util/bump-version.sh
Labels: skip-changelog-update

#2317 Rename redhat_ubi to redhat_on_docker
  cookbooks/aws-parallelcluster-awsbatch/recipes/awsbatch_virtualenv.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/install/parallelcluster_node.rb
  cookbooks/aws-parallelcluster-computefleet/test/controls/custom_parallelcluster_node_spec.rb
  cookbooks/aws-parallelcluster-computefleet/test/controls/node_spec.rb
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/efa_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_install_from_tar.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_install_lustre_centos_redhat.rb
  cookbooks/aws-parallelcluster-environment/resources/raid/partial/_raid_common.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_common.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_redhat8.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/efa_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/raid_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/awscli.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cookbook_virtualenv.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/partial/_chrony_common.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_common.rb
  cookbooks/aws-parallelcluster-platform/resources/stunnel/stunnel_redhat8.rb
  cookbooks/aws-parallelcluster-platform/test/controls/awscli_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/chrony_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/cluster_user_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/cookbook_virtualenv_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/install_packages_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/stunnel_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/test.rb
  cookbooks/aws-parallelcluster-shared/test/controls/install_pyenv_spec.rb
  cookbooks/aws-parallelcluster-shared/test/libraries/os_properties.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_jwt.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pmix.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_slurm.rb
  cookbooks/aws-parallelcluster-slurm/resources/jwt_dependencies/partial/_jwt_dependencies_common.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge/partial/_munge_actions.rb
  cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/partial/_slurm_dependencies_common.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/jwt_dependencies_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/jwt_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/munge_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/pmix_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/slurm_dependencies_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/slurm_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/slurm_users_spec.rb
  cookbooks/aws-parallelcluster-tests/recipes/docker_mock.rb
Labels: skip-changelog-update

#2319 Fix the kitchen test condition for ptrace_scope to switch on node type and add an efa kitchen test suite for the head node
  kitchen.resources-config.yml
  test/resources/controls/aws_parallelcluster_config/efa_spec.rb
Labels: skip-changelog-update

#2320 Fix system test config for efa, remove duplicate test in intel_mpi, tag ptrace control with 'config'
  kitchen.resources-config.yml
  kitchen.validate-config.yml
  test/recipes/controls/aws_parallelcluster_install/intel_mpi_spec.rb
  test/resources/controls/aws_parallelcluster_config/efa_spec.rb
Labels: skip-changelog-update

#2321 Fix system test config for efa, remove duplicate test in intel_mpi, add an efa kitchen test suite for the head node, updated the efa test swtich for head and compute node
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/test/controls/efa_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/intel_mpi_spec.rb
  kitchen.validate-config.yml
Labels: skip-changelog-update

#2322 [Ubuntu22] Add support for NVIDIA on Ubuntu 22
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/recipes/config/nvidia_uvm.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/nvidia_install.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_gdrcopy_spec.rb
Labels: skip-changelog-update

#2263 Increase size of default instance type
  kitchen.ec2.yml
  kitchen.validate-config.yml
Labels: skip-changelog-update

#2326 Fix raid_vol_array initialization
  cookbooks/aws-parallelcluster-environment/templates/shared_storages/shared_storages_data.erb
Labels: skip-changelog-update

#2294 Add partition-level Slurm configuration to run jobs on nodes exclusively allocated
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/config_renderer.py
  test/unit/slurm/test_slurm_config_generator.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_job_exc_alloc/cluster_config.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_job_exc_alloc/expected_outputs/pcluster/slurm_parallelcluster_queue_jls_default_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_job_exc_alloc/expected_outputs/pcluster/slurm_parallelcluster_queue_jls_disabled_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_job_exc_alloc/expected_outputs/pcluster/slurm_parallelcluster_queue_jls_enabled_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_job_exc_alloc/sample_instance_types_data.json
Labels: skip-changelog-update, 3.x

#2329 Export default ENV when PATH is required for command execution
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_alinux_centos.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_debian.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
Labels: skip-changelog-update

#2325 Relax Chef version requirements to use a more recent version of Chef/Cinc
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  metadata.rb
Labels: skip-changelog-update

#2333 Skip the failing features for the Ubuntu 22 AMI build
  cookbooks/aws-parallelcluster-entrypoints/kitchen.entrypoints-install.yml
  cookbooks/aws-parallelcluster-entrypoints/recipes/install.rb
  cookbooks/aws-parallelcluster-platform/recipes/install.rb
Labels: skip-changelog-update, skip-system-tests

#2335 Remove provisioner name
  kitchen.ec2.yml
Labels: skip-changelog-update, skip-system-tests

#2330 Deprecate support for Ubuntu18
  .github/workflows/dokken-system-tests.yml
  .github/workflows/dokken-validate.yml
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/efa_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/efs_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/ephemeral_drives/ephemeral_drives_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/network_service/network_service_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/network_service/network_service_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_ubuntu20+.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_setup_spec.rb
  cookbooks/aws-parallelcluster-platform/files/dcv/pcluster_dcv_connect.sh
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/arm_pl_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/build_tools/build_tools_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/build_tools/build_tools_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/c_states_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/chrony_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu18.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/nvidia_driver_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_repo/nvidia_repo_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_repo/nvidia_repo_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/stunnel/stunnel_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-shared/resources/os_type/os_type_ubuntu20+.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_ubuntu20+.rb
  cookbooks/aws-parallelcluster-shared/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-shared/test/libraries/os_properties.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_ubuntu20+.rb
  cookbooks/aws-parallelcluster-slurm/resources/jwt_dependencies/jwt_dependencies_ubuntu20+.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge/munge_ubuntu20+.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_client/mysql_client_ubuntu20+.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_ubuntu.rb
  cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_ubuntu20+.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/mysql_client_spec.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.docker.yml
  kitchen.ec2.sh
  kitchen.ec2.yml
  metadata.rb
  test/environments/kitchen.rb
Labels: skip-changelog-update, 3.x

#2311 Push instance-to-node mapping to cw log, configure new log group
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2192 Add job info daemon to supervisord conf, add configs and log files
  cookbooks/aws-parallelcluster-platform/templates/log_rotation/parallelcluster_log_rotation.erb
  cookbooks/aws-parallelcluster-platform/templates/supervisord/parallelcluster_supervisord.conf.erb
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_clusterjobinfomgtd.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/jobinfomgtd/parallelcluster_jobinfomgtd.conf.erb
Labels: skip-changelog-update, 3.x

#2338 Skip the failing features for the Ubuntu 22 AMI build in kitchen tests and skip the exit status for cloudwatch on Ubuntu 22
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/arm_pl_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
Labels: skip-changelog-update

#2337 Fix mock_compute shared storage recipes
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/test/mock_compute_ebs.rb
  cookbooks/aws-parallelcluster-environment/recipes/test/mock_compute_raid.rb
Labels: skip-changelog-update, skip-system-tests

#2332 Export default ENV when PATH is required for mdadm command execution
  cookbooks/aws-parallelcluster-environment/resources/raid/partial/_raid_common.rb
Labels: skip-changelog-update

#2339 Split resources and recipes tests
  cookbooks/aws-parallelcluster-awsbatch/kitchen.awsbatch-config.yml
  cookbooks/aws-parallelcluster-awsbatch/kitchen.awsbatch-install.yml
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-config.yml
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-install.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-shared/kitchen.shared-config.yml
  cookbooks/aws-parallelcluster-shared/kitchen.shared-install.yml
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-install.yml
Labels: skip-changelog-update, skip-system-tests

#2341 Replace nvidia-persistenced service with parallelcluster_nvidia service to avoid conflicts with DLAMI
  cookbooks/aws-parallelcluster-config/recipes/nvidia.rb
  cookbooks/aws-parallelcluster-config/templates/default/nvidia/parallelcluster_nvidia_service.erb
  cookbooks/aws-parallelcluster-slurm/recipes/config_slurmd_systemd_service.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/compute/slurmd_nvidia_persistenced.conf.erb
  libraries/helpers.rb
  test/recipes/controls/aws_parallelcluster_config/nvidia_spec.rb
  test/recipes/controls/aws_parallelcluster_slurm/config_slurmd_systemd_service_spec.rb
Labels: skip-changelog-update
