Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-09, with the labels that each got.

#2448 [release-3.7][unit-tests] Remove pytest HTML report from tox
  test/unit/requirements.txt
  tox.ini
Labels: skip-changelog-update

#2447 [develop][unit-tests] Remove pytest HTML report from tox
  test/unit/requirements.txt
  tox.ini
Labels: skip-changelog-update

#2444 Added hash of scripts to logging
  cookbooks/aws-parallelcluster-environment/files/custom_action_executor/custom_action_executor.py
Labels: skip-changelog-update, 3.x

#2429 add developer environment for vscode
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
Labels: skip-changelog-update

#2449 Fixes for CodeQL
  cookbooks/aws-parallelcluster-computefleet/files/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config_util.py
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2455 [release-3.7]Bump version to 3.7.1
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: skip-changelog-update

#2445 Add unit tests for cookbook EBS related scripts
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/manageVolume.py
  test/unit/ec2_udev_rules/test_ec2_dev_2_volid.py
  test/unit/ec2_udev_rules/test_manage_volume.py
Labels: skip-changelog-update, 3.x

#2451 [develop] Add custom munge key config logic
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_munge_key.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge_key_manager.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/munge_spec.rb
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x

#2452 [develop] Add custom munge key update logic
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/libraries/update.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge_key_manager.rb
Labels: skip-changelog-update, 3.x

#2453 [develop] Add custom munge key rotation script
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x

#2466 [develop] Add validator in rotation script to check custom munge key size
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x

#2468 Add logic in rotation script of checking if compute fleet STOPPED
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x

#2467 [develop] Share the munge key from the Parallel Cluster shared folder
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/libraries/update.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_login.rb
  cookbooks/aws-parallelcluster-slurm/recipes/test/mock_munge_key.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x

#2474 [Rocky] Update CHANGELOG and handle unsupported kernel version for Fsx Lustre Client
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_rocky8.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_rocky8.rb
  kitchen.docker.yml
  test/environments/kitchen.rb
Labels: 3.x
