Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-01, with the labels that each got.

#1632 [head node bootstrap errors] store custom script errors
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
Labels: skip-changelog-update, 3.x

#1635 [Versioning] Bump version to 3.4.1
  attributes/default.rb
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-install/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-test/metadata.rb
  metadata.rb
Labels: skip-changelog-update

#1598 3.x Add configuration to clustermgtd.conf for collecting compute console output.
  attributes/default.rb
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_log_files.json
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
Labels: skip-changelog-update, 3.x

#1636 [develop] Increase retries and delay for gcc download
  cookbooks/aws-parallelcluster-install/recipes/arm_pl.rb
Labels: skip-changelog-update

#1640 [3.x] Add metadata options to disable imdsv1
  .kitchen.cloud.yml
Labels: skip-changelog-update

#1645 [develop] Throw specific Exception instead of generic one
  .flake8
  cookbooks/aws-parallelcluster-install/files/default/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_fleet_config_generator.py
  test/unit/clusterstatusmgtd/test_clusterstatusmgtd.py
  test/unit/slurm/test_fleet_config_generator.py
Labels: skip-changelog-update

#1646 Remove deprecated unused script: chef-install.sh
  util/chef-install.sh
Labels: skip-changelog-update, 3.x

#1648 Add execution of dokken tests as GitHub action
  .github/workflows/ci.yml
Labels: skip-changelog-update

#1652 Add redhat8 to kitchen dokken GitHub action
  .github/workflows/ci.yml
  kitchen.docker.yml
  test/Dockerfile.rhel8
Labels: skip-changelog-update

#1651 3.x Fix console output configuration error
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
Labels: skip-changelog-update, 3.x

#1659 Use global attributes in kitchen config.
  .github/workflows/ci.yml
  cookbooks/aws-parallelcluster-install/resources/package_repos/package_repos_redhat8.rb
  kitchen.docker.yml
  kitchen.global.yml
  kitchen.recipes.yml
  kitchen.resources.yml
  test/resources/controls/aws_parallelcluster_install/package_repos_spec.rb
Labels: skip-changelog-update

#1660 Add directories.rb recipe extracting from base.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/directories.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/directories_spec.rb
Labels: skip-changelog-update

#1663 3.x Fix failure when missing cloudwatch in dna.json
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
Labels: skip-changelog-update, 3.x

#1664 Remove SSH subsystem override
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
Labels: skip-changelog-update

#1667 Allow running kitchen tests with default parameters
  .gitignore
  kitchen.ec2.sh
  kitchen.ec2.yml
  util/bump-version.sh
Labels: skip-changelog-update

#1668 Refactor and test aws-parallelcluster-install::python recipe
  Berksfile
  attributes/default.rb
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/python.rb
  kitchen.docker.sh
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/python_spec.rb
Labels: skip-changelog-update, 3.x

#1671 Create custom resource os_properties to expose common os properties used in tests
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  test/common/inspec.yml
  test/common/libraries/os_properties.rb
  test/recipes/controls/aws_parallelcluster_install/python_spec.rb
  test/recipes/inspec.yml
  test/resources/inspec.yml
Labels: skip-changelog-update, 3.x

#1670 Add resource install_packages compatible with RedHat8
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_amazon2.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_centos7.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/partial/_install_packages_debian.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/partial/_install_packages_rhel_amazon.rb
  test/common/libraries/os_properties.rb
  test/resources/controls/aws_parallelcluster_install/install_packages_spec.rb
Labels: skip-changelog-update

#1673 Move supervisord setup into a separate recipe
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/supervisord.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/supervisord_spec.rb
Labels: skip-changelog-update, 3.x

#1676 Move awscli installation into a new awscli.rb recipe
  cookbooks/aws-parallelcluster-install/recipes/awscli.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/awscli_spec.rb
Labels: skip-changelog-update, 3.x

#1679 Add node attributes json generation in /etc/chef/node_attributes.json
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/resources/node_attributes/node_attributes.rb
  test/resources/controls/aws_parallelcluster_install/node_attributes_spec.rb
Labels: skip-changelog-update

#1680 Remove mysql and mariadb libraries from base packages on all OSs
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
Labels: skip-changelog-update, 3.x

#1684 Remove mysql and mariadb devel packages from system tests dockerfiles
  system_tests/Dockerfile.centos7
  system_tests/Dockerfile.ubuntu
Labels: skip-changelog-update, 3.x

#1691 Add environment-modules package because intel_mpi recipe relies on it
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
Labels: skip-changelog-update

#1692 Remove OnOndeStart and OnNodeConfigured scripts url from showing up in CFN failure reason
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
Labels: skip-changelog-update, 3.x

#1693 Add test for clusterstatusmgtd recipe
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/clusterstatusmgtd_spec.rb
Labels: skip-changelog-update, 3.x

#1694 Install MySQL packages from OS repos for Ubuntu x86_64
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/install_mysql_client.rb
  cookbooks/aws-parallelcluster-test/recipes/validate_mysql.rb
Labels: skip-changelog-update, 3.x

#1666 [bandit] Add ec2_udev_rules directory for bandit scanning
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/common.py
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/manageVolume.py
  tox.ini
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#1690 [bandit] Explain reason for security exclusion in dcv unit test
  test/unit/dcv/test_dcv_authenticator.py
Labels: skip-changelog-update, skip-security-exclusions-check

#1683 Fix version bump script to change version in common cookbook attributes
  util/bump-version.sh
Labels: skip-changelog-update

#1701 Upgrade Slurm to version 22.05.8
  CHANGELOG.md
  attributes/default.rb
Labels: 3.x

#1699 Ad test for cron recipe
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/cron_spec.rb
Labels: skip-changelog-update, 3.x

#1697 Add test and validate recipe chrony for RedHat 8
  cookbooks/aws-parallelcluster-install/recipes/chrony.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_install/chrony_spec.rb
Labels: skip-changelog-update

#1698 Add test for mysql-client resource
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/recipes/install_mysql_client.rb
  cookbooks/aws-parallelcluster-install/recipes/install_mysql_repository.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/mysql_client.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/mysql_client_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_download_and_install.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_source_link.rb
  kitchen.resources.yml
  test/common/libraries/os_properties.rb
  test/resources/controls/aws_parallelcluster_install/mysql_client_spec.rb
Labels: skip-changelog-update, 3.x

#1704 Add test and validate c_states resource for RedHat 8
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/c_states.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_amazon2.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_centos7.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_ubuntu20.rb
  kitchen.resources.yml
  test/common/libraries/os_properties.rb
  test/resources/controls/aws_parallelcluster_install/c_states_spec.rb
Labels: skip-changelog-update
