Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-12, with the labels that each got.

#2583 [Test] Add Rocky8 to tests.
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/ephemeral_drives_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/network_service_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/nfs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/raid_mount_unmount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/system_authentication_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/install_packages_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/modules_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_repo_spec.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_rocky8.rb
  cookbooks/aws-parallelcluster-shared/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/os_type_spec.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/package_repos_spec.rb
Labels: skip-changelog-update, 3.x

#2584 [Test] Add Rocky8 to tests.
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/ephemeral_drives_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/network_service_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/nfs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/raid_mount_unmount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/system_authentication_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/install_packages_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/modules_spec.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_repo_spec.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_rocky8.rb
  cookbooks/aws-parallelcluster-shared/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/os_type_spec.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/package_repos_spec.rb
Labels: skip-changelog-update, 3.x

#2591 Remove obsolete params from slurm config
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/cgroup.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update, 3.x

#2590 [release-3.8] Use Slurm install dir variable in update_slurm_database_password.sh
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_slurm_database_password.sh.erb
Labels: 3.x

#2589 [develop] Use Slurm install dir variable in update_slurm_database_password.sh
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_slurm_database_password.sh.erb
Labels: 3.x

#2594 Build Slurm from development branch `slurm-23.02`
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
Labels: skip-changelog-update, 3.x

#2597 [release-3.8] Install kernel-devel for Rocky Linux from vault
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
Labels: skip-changelog-update

#2599 [develop] Add support for passing Slurm patches from S3
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_slurm.rb
Labels: skip-changelog-update, 3.x

#2596 [release-3.8] Add support for passing Slurm patches from S3
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_slurm.rb
Labels: skip-changelog-update, 3.x

#2600 [release-3.8] Upgrade slurm version to 23.02.7
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_slurm.rb
Labels: 3.x

#2602 [release-3.8] Avoid to exit while trying to install a specific kernel-devel version
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
Labels: skip-changelog-update

#2603 [release-3.8] Avoid to exit while trying to install a specific kernel-devel version
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
Labels: skip-changelog-update

#2609 [develop] Remove `mysql_repo` resource
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-install.yml
  cookbooks/aws-parallelcluster-slurm/recipes/install.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/mysql_repo_amazon2.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/mysql_repo_centos7.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/mysql_repo_redhat8.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/mysql_repo_rocky8.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/mysql_repo_ubuntu20+.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/partial/_mysql_repo_deb.rb
  cookbooks/aws-parallelcluster-slurm/resources/mysql_repo/partial/_mysql_repo_rpm.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/mysql_repo_spec.rb
Labels: skip-changelog-update, 3.x

#2610 Use noninteractive mode when using pam-auth-update for debian
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_debian.rb
Labels: skip-changelog-update
