Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-05, with the labels that each got.

#2045 [release-3.6]Add check for GPU not supported by DCGM
  cookbooks/aws-parallelcluster-common/test/common/libraries/instance.rb
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/health_checks/gpu_health_check.sh
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2046 [release-3.6]Fix kitchen test for GPU check
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2047 [develop]Fix kitchen test for GPU check
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2048 Fix validate-config kitchen tests
  kitchen.validate-config.yml
  recipes/add_dependencies.rb
Labels: skip-changelog-update, 3.x

#2049 [develop]Fix kitchen test for ARM on alinux2/centos7
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/health_checks/gpu_health_check.sh
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2050 [release-3.6]Fix kitchen test for ARM on alinux2/centos7
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/health_checks/gpu_health_check.sh
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2051 Generate ChefSpec coverage report
  .rubocop.yml
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
Labels: skip-changelog-update, 3.x

#2055 [develop]Fix gpu check kitchen test
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2056 [release-3.6]Fix gpu check kitchen test
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/config_health_check_spec.rb
Labels: skip-changelog-update

#2058 Fallback to KITCHEN_ARCHITECTURE default value
  kitchen.ec2.sh
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2059 Check MySQL package version
  cookbooks/aws-parallelcluster-common/test/common/libraries/os_properties.rb
  test/resources/controls/aws_parallelcluster_install/mysql_client_spec.rb
Labels: skip-changelog-update, 3.x

#2062 Tag mysql_client controls with tag:install
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_install/mysql_client_spec.rb
Labels: skip-changelog-update, 3.x

#2063 Cleanup unused code
  cookbooks/aws-parallelcluster-install/resources/mysql_client/mysql_client.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/mysql_client_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_validate.rb
  cookbooks/aws-parallelcluster-install/spec/unit/resources/mysql_client_spec.rb
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/recipes/validate_mysql.rb
  cookbooks/aws-parallelcluster-test/recipes/validations.rb
  recipes/validations.rb
Labels: skip-changelog-update, 3.x

#2064 Add tag:install to arm_pl controls
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_install/arm_pl_spec.rb
Labels: skip-changelog-update, 3.x

#2065 Inject correct region into mysql_client source code control
  test/resources/controls/aws_parallelcluster_install/mysql_client_spec.rb
Labels: skip-changelog-update, 3.x

#2066 Kitchen tests cleanup
  cookbooks/aws-parallelcluster-common/recipes/add_dependencies.rb
  kitchen.recipes-config.yml
  kitchen.recipes-install.yml
  kitchen.resources-install.yml
  recipes/add_dependencies.rb
  recipes/test_resource.rb
Labels: skip-changelog-update, 3.x

#2070 Bump version to 3.6.0
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  kitchen.ec2.yml
  system_tests/systemd
Labels: skip-changelog-update

#2071 Inject correct region into mysql_client source code control
  test/resources/controls/aws_parallelcluster_install/mysql_client_spec.rb
Labels: skip-changelog-update, 3.x

#2072 [develop] Use junit2 to collect Inspec results
  kitchen.global.yml
Labels: skip-changelog-update

#2078 Skip kitchen test for root volume space on Centos7 x86
  test/recipes/controls/other_spec.rb
Labels: skip-changelog-update

#2077 Create aws-parallelcluster-tests cookbook, to be used to setup Kitchen tests
  Berksfile
  cookbooks/aws-parallelcluster-shared/resources/node_attributes.rb
  cookbooks/aws-parallelcluster-tests/Berksfile
  cookbooks/aws-parallelcluster-tests/metadata.rb
  cookbooks/aws-parallelcluster-tests/recipes/setup.rb
  util/bump-version.sh
Labels: skip-changelog-update, 3.x

#2083 Move disable_services from aws-parallelcluster-install to aws-parallelcluster-platform
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/recipes/install/disable_services.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/disable_services_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/disable_services_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/test.rb
  kitchen.recipes-install.yml
Labels: skip-changelog-update, 3.x

#2087 Fix InSpec intel_mpi_installed test
  kitchen.recipes-install.yml
  test/recipes/controls/aws_parallelcluster_install/intel_mpi_spec.rb
Labels: skip-changelog-update

#2088 Fix InSpec intel_mpi_installed test
  kitchen.recipes-install.yml
  test/recipes/controls/aws_parallelcluster_install/intel_mpi_spec.rb
Labels: skip-changelog-update

#2091 Remove dependency on test_dummy from fs_update_default_values
  kitchen.recipes-config.yml
Labels: skip-changelog-update, 3.x

#2095 Fix ephemeral_drives InSpec test
  test/recipes/controls/aws_parallelcluster_config/ephemeral_drives_spec.rb
Labels: skip-changelog-update

#2096 Create install_pyenv in shared cookbook
  .github/workflows/ci.yml
  cookbooks/aws-parallelcluster-common/Berksfile
  cookbooks/aws-parallelcluster-shared/Berksfile
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-shared/recipes/default.rb
  cookbooks/aws-parallelcluster-shared/resources/install_pyenv.rb
  cookbooks/aws-parallelcluster-shared/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/install_pyenv_spec.rb
Labels: skip-changelog-update, 3.x

#2094 [3.x] Move unmount from tests.rb to a separate file
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  kitchen.validate-config.yml
  recipes/unmount_home.rb
Labels: skip-changelog-update

#2098 Fix Kitchen config for Ubuntu22
  README.md
  kitchen.docker.yml
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2099 First draft Ubuntu 22 resources
  cookbooks/aws-parallelcluster-common/attributes/common_ubuntu.rb
  cookbooks/aws-parallelcluster-common/attributes/common_ubuntu18.rb
  cookbooks/aws-parallelcluster-common/resources/cloudwatch/cloudwatch_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_ubuntu18.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_ubuntu20+.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/fabric_manager/fabric_manager_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/gdrcopy/gdrcopy_ubuntu22.rb
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/network_service/network_service_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_ubuntu.rb
  cookbooks/aws-parallelcluster-config/resources/manage_raid/manage_raid_ubunu20+.rb
  cookbooks/aws-parallelcluster-config/resources/sticky_bits/sticky_bits_ubuntu20+.rb
  cookbooks/aws-parallelcluster-config/resources/sticky_bits/sticky_bits_ubuntu2004.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu22.rb
  cookbooks/aws-parallelcluster-install/resources/arm_pl/arm_pl_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/arm_pl/arm_pl_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/ec2_udev_rules/ec2_udev_rules_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/ec2_udev_rules/ec2_udev_rules_ubuntu1804.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/modules/modules_ubuntu20+.rb
  cookbooks/aws-parallelcluster-install/resources/modules/modules_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/nvidia_dcgm/nvidia_dcgm_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/nvidia_dcgm/nvidia_dcgm_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/nvidia_driver/nvidia_driver_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/nvidia_driver/nvidia_driver_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/resources/nvidia_driver/nvidia_driver_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/stunnel_ubuntu.rb
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2102 Restore efs dependencies
  kitchen.resources-config.yml
Labels: skip-changelog-update, 3.x

#2103 Copy package_repos suite into main resources-install
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_install/package_repos_spec.rb
Labels: skip-changelog-update, 3.x

#2100 [develop] Set dependency between slurmd and nvidia-persistenced
  cookbooks/aws-parallelcluster-slurm/recipes/config_compute.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_slurmd_systemd_service.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/compute/slurmd_nvidia_persistenced.conf.erb
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/config_slurmd_systemd_service_spec.rb
Labels: skip-changelog-update, 3.x

#2104 Move activate_virtual_env to shared cookbook
  cookbooks/aws-parallelcluster-shared/resources/activate_virtual_env.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/activate_virtual_env_spec.rb
Labels: skip-changelog-update, 3.x

#2105 Remove attribute set from install_pyenv
  cookbooks/aws-parallelcluster-shared/resources/install_pyenv.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/install_pyenv_spec.rb
Labels: skip-changelog-update, 3.x

#2107 Move Kitchen test on cookbook_virtualenv to platform cookbook
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  kitchen.recipes-install.yml
Labels: skip-changelog-update, 3.x

#2108 Move cfn_bootstrap to environment cookbook
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/cfn-hup-runner.sh.erb
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/pcluster.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/cfn_bootstrap.rb
  kitchen.recipes-install.yml
Labels: skip-changelog-update, 3.x

#2110 Replace node['cluster']['cookbook_virtualenv_path'] with function
  cookbooks/aws-parallelcluster-awsbatch/recipes/install.rb
  cookbooks/aws-parallelcluster-common/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/install/node.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_fleet_status.rb
  cookbooks/aws-parallelcluster-config/resources/fetch_config.rb
  cookbooks/aws-parallelcluster-config/resources/manage_ebs.rb
  cookbooks/aws-parallelcluster-config/resources/manage_raid/partial/_raid_configuration.rb
  cookbooks/aws-parallelcluster-config/resources/volume/volume.rb
  cookbooks/aws-parallelcluster-config/spec/unit/resources/manage_raid_mount_unmount_spec.rb
  cookbooks/aws-parallelcluster-config/spec/unit/resources/volume_spec.rb
  cookbooks/aws-parallelcluster-config/templates/default/base/parallelcluster_supervisord.conf.erb
  cookbooks/aws-parallelcluster-config/templates/default/compute_fleet_status/get-compute-fleet-status.erb
  cookbooks/aws-parallelcluster-config/templates/default/compute_fleet_status/update-compute-fleet-status.erb
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  cookbooks/aws-parallelcluster-install/recipes/awscli.rb
  cookbooks/aws-parallelcluster-install/templates/default/base/supervisord-service.erb
  cookbooks/aws-parallelcluster-install/templates/default/ec2_udev_rules/ec2-volid.rules.erb
  cookbooks/aws-parallelcluster-install/templates/default/ec2_udev_rules/parallelcluster-ebsnvme-id.erb
  cookbooks/aws-parallelcluster-platform/recipes/install/cookbook_virtualenv.rb
  cookbooks/aws-parallelcluster-platform/test/controls/cookbook_virtualenv_spec.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/resources/fetch_artifacts.rb
  cookbooks/aws-parallelcluster-shared/libraries/environment.rb
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_computefleet_status_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/resources/remote_object/remote_object.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/health_check/90_pcluster_health_check_manager.erb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update, 3.x

#2113 Check if NVIDIA is enabled in the NVIDIA-related control
  test/recipes/controls/aws_parallelcluster_config/nvidia_spec.rb
Labels: skip-changelog-update, 3.x

#2114 Dump node_attributes to be used by InSpec tests
  cookbooks/aws-parallelcluster-tests/recipes/tear_down.rb
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x

#2115 Enable saving image after Kitchen test
  README.md
  kitchen.docker.yml
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2111 Improve kitchen tests for slurmd systemd configuration
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_slurm/config_slurmd_systemd_service_spec.rb
Labels: skip-changelog-update, 3.x

#2124 Remove python package from Ubuntu22 default packages, align stunnel test name with our current pattern
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu22.rb
  kitchen.resources-install.yml
Labels: skip-changelog-update

#2126 Add ubuntu2204? method, add ubuntu2204 to the sticky bits resource test, add the comment to include a custom ubuntu22 image
  cookbooks/aws-parallelcluster-common/test/common/libraries/os_properties.rb
  kitchen.docker.yml
  kitchen.ec2.sh
  test/resources/controls/aws_parallelcluster_config/sticky_bits_spec.rb
Labels: skip-changelog-update

#2130 Move openssh from install to platform cookbook
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/openssh.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/test/controls/openssh_spec.rb
  cookbooks/aws-parallelcluster-tests/recipes/docker_mock.rb
  cookbooks/aws-parallelcluster-tests/recipes/setup.rb
  kitchen.recipes-install.yml
  kitchen.validate-install.yml
Labels: skip-changelog-update, 3.x

#2132 Move license_readme from install to platform cookbook
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-platform/files/AWS-ParallelCluster-License-README.txt
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/recipes/install/license_readme.rb
  cookbooks/aws-parallelcluster-platform/test/controls/license_readme_spec.rb
  kitchen.recipes-install.yml
  kitchen.validate-install.yml
Labels: skip-changelog-update, 3.x

#2134 Add recipe: qualifier to aws-parallelcluster-platform::cookbook_virtualenv dependency
  kitchen.recipes-config.yml
  kitchen.recipes-install.yml
  kitchen.resources-config.yml
Labels: skip-changelog-update, 3.x

#2122 [3.x] Removal of tests.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu22.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_awsbatch/awsbatch_spec.rb
  test/recipes/controls/other_spec.rb
Labels: skip-changelog-update

#2136 remove missing package from deps for pyenv in ubuntu 22
  third-party/pyenv-3.5.1/attributes/default.rb
Labels: skip-changelog-update

#2138 Rename validate config test suites
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x

#2142 Fix default user for AMI build
  cookbooks/aws-parallelcluster-shared/attributes/users.rb
  cookbooks/aws-parallelcluster-shared/attributes/users_amazon2.rb
  cookbooks/aws-parallelcluster-shared/attributes/users_centos7.rb
  cookbooks/aws-parallelcluster-shared/attributes/users_redhat8.rb
  cookbooks/aws-parallelcluster-shared/attributes/users_ubuntu.rb
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2137 Refactor nvidia fabric manager and gdrcopy out of nvidia spec. Add lustre spec to global config.
  kitchen.recipes-install.yml
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_install/fabric_manager_spec.rb
  test/resources/controls/aws_parallelcluster_install/gdrcopy_spec.rb
  test/resources/controls/aws_parallelcluster_install/lustre_spec.rb
  test/resources/controls/aws_parallelcluster_install/nvidia_spec.rb
Labels: skip-changelog-update

#2135 Skip System tests depending on the label
  .github/workflows/dokken-system-tests.yml
Labels: skip-changelog-update, 3.x

#2144 Add user in awscli "can run as" test description
  cookbooks/aws-parallelcluster-platform/test/controls/awscli_spec.rb
Labels: skip-changelog-update, 3.x

#2151 Skip system tests steps if skip_system_tests label is set
  .github/workflows/dokken-system-tests.yml
Labels: skip-changelog-update, 3.x

#2149 Add network service kitchen tests
  cookbooks/aws-parallelcluster-common/resources/network_service/partial/_network_service_debian.rb
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_common/network_service_spec.rb
Labels: skip-changelog-update

#2147 Align naming of kitchen.ec2.yml to the one in kitchen.docker.yml
  .github/workflows/dokken-unit-tests.yml
  .github/workflows/dokken-validate.yml
  README.md
  kitchen.ec2.sh
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2154 [release-3.6] Fix EFA installation on RHEL8
  cookbooks/aws-parallelcluster-common/resources/efa/efa_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/efa/partial/_setup.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  test/resources/controls/aws_parallelcluster_install/efa_spec.rb
Labels: skip-changelog-update

#2156 [develop] Fix EFA installation on RHEL8
  cookbooks/aws-parallelcluster-common/resources/efa/efa_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_ubuntu.rb
  cookbooks/aws-parallelcluster-common/resources/efa/partial/_setup.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  test/resources/controls/aws_parallelcluster_install/efa_spec.rb
Labels: skip-changelog-update

#2157 Move ami_cleanup from install to platform cookbook
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/default.rb
  cookbooks/aws-parallelcluster-install/spec/unit/recipes/ami_cleanup_spec.rb
  cookbooks/aws-parallelcluster-install/spec/unit/recipes/fake_spec.rb
  cookbooks/aws-parallelcluster-platform/files/ami_cleanup.sh
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/recipes/install/ami_cleanup.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/ami_cleanup_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/ami_cleanup_spec.rb
  kitchen.recipes-install.yml
  kitchen.validate-install.yml
Labels: skip-changelog-update, 3.x

#2162 Move alinux_extras_topic to shared cookbook
  cookbooks/aws-parallelcluster-shared/resources/alinux_extras_topic.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/alinux_extras_topic_spec.rb
Labels: skip-changelog-update, 3.x

#2159 Add kernel version for RHEL 8.8
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_redhat8.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_setup_spec.rb
Labels: skip-changelog-update

#2160 Add kernel version for RHEL 8.8
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_redhat8.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_setup_spec.rb
Labels: skip-changelog-update

#2163 Move package_repos to shared cookbook
  cookbooks/aws-parallelcluster-common/kitchen.resources.yml
  cookbooks/aws-parallelcluster-common/test/resources/controls/package_repos_spec.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-shared/kitchen.shared-install.yml
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_alinux2.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_centos7.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_redhat8.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/package_repos_ubuntu.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/partial/_package_repos_deb.rb
  cookbooks/aws-parallelcluster-shared/resources/package_repos/partial/_package_repos_rpm.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/package_repos_spec.rb
  cookbooks/aws-parallelcluster-shared/test/controls/package_repos_spec.rb
  kitchen.resources-install.yml
Labels: skip-changelog-update, 3.x, skip-system-tests

#2161 Move chrony to platform cookbook and transform it into resource
  .github/workflows/dokken-unit-tests.yml
  cookbooks/aws-parallelcluster-common/attributes/common_amazon2.rb
  cookbooks/aws-parallelcluster-common/attributes/common_centos7.rb
  cookbooks/aws-parallelcluster-common/attributes/common_redhat8.rb
  cookbooks/aws-parallelcluster-common/attributes/common_ubuntu.rb
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/recipes/chrony.rb
  cookbooks/aws-parallelcluster-config/recipes/default.rb
  cookbooks/aws-parallelcluster-config/spec/unit/recipes/chrony_spec.rb
  cookbooks/aws-parallelcluster-config/spec/unit/recipes/fake_spec.rb
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu22.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/chrony.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-platform/recipes/default.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/chrony_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/chrony_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/chrony_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/chrony_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/chrony/partial/_chrony_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/chrony_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/chrony_spec.rb
  kitchen.recipes-config.yml
  kitchen.recipes-install.yml
  kitchen.validate-install.yml
  test/recipes/controls/aws_parallelcluster_config/chrony_spec.rb
Labels: skip-changelog-update, 3.x

#2164 Use tag:config_chrony controls on the config path
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/test/controls/chrony_spec.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2165 Move modules to platform cookbook
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/modules/modules_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/modules/modules_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/modules/modules_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/modules/modules_ubuntu18.rb
  cookbooks/aws-parallelcluster-platform/resources/modules/modules_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/modules/partial/_modules_apt.rb
  cookbooks/aws-parallelcluster-platform/resources/modules/partial/_modules_yum.rb
  cookbooks/aws-parallelcluster-platform/test/controls/modules_spec.rb
  kitchen.resources-install.yml
Labels: skip-changelog-update, 3.x

#2167 Move c_states to platform cookbook
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-common/resources/dcv/dcv_ubuntu20+.rb
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/partial/_c_states_common.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/c_states/c_states_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/c_states_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/c_states_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/c_states_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/partial/_c_states_common.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/partial/_c_states_debian.rb
  cookbooks/aws-parallelcluster-platform/resources/c_states/partial/_c_states_redhat_based.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/c_states_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/c_states_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/environment.rb
  kitchen.resources-install.yml
  kitchen.validate-install.yml
Labels: skip-changelog-update, 3.x

#2168 Fix to c_states
  cookbooks/aws-parallelcluster-platform/resources/c_states/partial/_c_states_common.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2170 Move nfs to environment cookbook
  attributes/default.rb
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-environment/recipes/default.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/nfs_alinux2.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/nfs_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/nfs_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/nfs_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/partial/_configure.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/partial/_install_nfs4_and_disable.rb
  cookbooks/aws-parallelcluster-environment/resources/nfs/partial/_install_nfs_debian.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/nfs_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/nfs/nfs.conf.erb
  cookbooks/aws-parallelcluster-environment/test/controls/nfs_spec.rb
  kitchen.resources-config.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_install/nfs_spec.rb
Labels: skip-changelog-update, 3.x

#2173 Add Ubuntu22.04 capability to ChefSpec tests
  cookbooks/aws-parallelcluster-environment/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/isolated_install_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/ephemeral_drives_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/nfs_spec.rb
  cookbooks/aws-parallelcluster-shared/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-shared/spec/ubuntu.22.json
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/activate_virtual_env_spec.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/install_pyenv_spec.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/package_repos_spec.rb
Labels: skip-changelog-update, 3.x

#2175 Move ec2_udev_rules to environment cookbook
  README.md
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/ec2blkdev-init
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/manageVolume.py
  cookbooks/aws-parallelcluster-environment/files/ubuntu/ec2_udev_rules/ec2blkdev-init
  cookbooks/aws-parallelcluster-environment/files/ubuntu/ec2_udev_rules/udev-override.conf
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_alinux2.rb
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/partial/_common_udev_configuration.rb
  cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/partial/_debian_udev_configuration.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/ec2_udev_rules_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/ec2_udev_rules/ec2-volid.rules.erb
  cookbooks/aws-parallelcluster-environment/templates/ec2_udev_rules/parallelcluster-ebsnvme-id.erb
  cookbooks/aws-parallelcluster-environment/test/controls/ec2_udev_rules_spec.rb
  cookbooks/aws-parallelcluster-install/templates/default/ec2_udev_rules/ec2-volid.rules.erb
  kitchen.validate-install.yml
  tox.ini
Labels: skip-changelog-update, 3.x

#2176 Move cloudwatch to environment cookbook
  attributes/default.rb
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config_schema.json
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config_util.py
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_alinux2.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_install_package_debian.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_install_package_rhel.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-shared/attributes/cluster.rb
  cookbooks/aws-parallelcluster-shared/attributes/directories.rb
  kitchen.resources-config.yml
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_install/cloudwatch_spec.rb
  tox.ini
Labels: skip-changelog-update, 3.x

#2127 Introduce Slurm compute node priority customization
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/config_renderer.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_efa_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_efa_partition_mem_sched.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_gpu_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_gpu_partition_mem_sched.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_multiple_spot_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/expected_outputs/pcluster/slurm_parallelcluster_multiple_spot_partition_mem_sched.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_memory_scheduling/sample_input_mem_sched.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/expected_outputs/pcluster/slurm_parallelcluster_efa_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/expected_outputs/pcluster/slurm_parallelcluster_gpu_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/expected_outputs/pcluster/slurm_parallelcluster_gpu_partition_no_gpu.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/expected_outputs/pcluster/slurm_parallelcluster_multiple_spot_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_nogpu/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input_slurm_accounting.yaml
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_custom_settings/expected_outputs/pcluster/slurm_parallelcluster_efa_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_custom_settings/expected_outputs/pcluster/slurm_parallelcluster_gpu_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_custom_settings/expected_outputs/pcluster/slurm_parallelcluster_multiple_spot_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_custom_settings/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue1_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue2_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue3_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue4_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue5_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue6_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue7_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/expected_outputs/pcluster/slurm_parallelcluster_queue8_partition.conf
  test/unit/slurm/test_slurm_config_generator/test_generating_slurm_config_flexible_instance_types/sample_input.yaml
Labels: 3.x

#2178 Move arm_pl to platform cookbook
  cookbooks/aws-parallelcluster-install/attributes/default.rb
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/arm_pl_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/arm_pl_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/arm_pl_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/arm_pl_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/partial/_arm_pl_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/arm_pl_spec.rb
  cookbooks/aws-parallelcluster-platform/templates/arm_pl/armpl_modulefile.erb
  cookbooks/aws-parallelcluster-platform/templates/arm_pl/gcc_modulefile.erb
  cookbooks/aws-parallelcluster-platform/test/controls/arm_pl_spec.rb
Labels: skip-changelog-update, 3.x

#2183 [develop] Add new cookbooks as deps of the main one
  Berksfile
  metadata.rb
Labels: skip-changelog-update

#2187 Move lustre resource from common to environment cookbook
  cookbooks/aws-parallelcluster-common/kitchen.resources.yml
  cookbooks/aws-parallelcluster-common/test/resources/controls/lustre_spec.rb
  cookbooks/aws-parallelcluster-common/test/resources/inspec.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_alinux2.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_install_lustre_centos_redhat.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_install_lustre_debian.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_setup_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/helpers.rb
  kitchen.resources-install.yml
Labels: skip-changelog-update

#2188 Move efa resource to environment cookbook
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-common/libraries/networking.rb
  cookbooks/aws-parallelcluster-common/resources/efa/partial/_setup.rb
  cookbooks/aws-parallelcluster-common/test/common/libraries/instance.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/resources/efa/efa_alinux2.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/efa_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/efa_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/efa_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/partial/_common.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/partial/_disable_ptrace_debian.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/efa_spec.rb
  kitchen.resources-config.yml
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_config/efa_spec.rb
Labels: skip-changelog-update, 3.x

#2189 Allow aws-parallelcluster-tests::test_resource to accept properties
  cookbooks/aws-parallelcluster-tests/recipes/test_resource.rb
Labels: skip-changelog-update, 3.x

#2191 Restructure CloudWatch Inspec test to avoid failures on Ubuntu20
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2193 Fix nfs test to pass on every instance type
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/test/controls/nfs_spec.rb
Labels: skip-changelog-update

#2180 Move openssh from config to platform cookbook
  cookbooks/aws-parallelcluster-common/libraries/networking.rb
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/recipes/openssh.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/openssh_spec.rb
  cookbooks/aws-parallelcluster-platform/templates/openssh/ssh_target_checker.sh.erb
  cookbooks/aws-parallelcluster-platform/test/controls/ssh_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/networking.rb
  kitchen.recipes-config.yml
  recipes/update.rb
Labels: skip-changelog-update, 3.x

#2196 Move system_authentication resource to environment cookbook
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_alinux_centos.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_common.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/partial/_system_authentication_debian.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_alinux2.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_centos7.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_ubuntu.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/system_authentication_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb
  kitchen.resources-config.yml
  kitchen.validate-install.yml
Labels: skip-changelog-update, 3.x

#2200 Move fabric_manager resource to platform cookbook
  cookbooks/aws-parallelcluster-common/attributes/common_amazon2.rb
  cookbooks/aws-parallelcluster-common/attributes/common_centos7.rb
  cookbooks/aws-parallelcluster-common/attributes/common_redhat8.rb
  cookbooks/aws-parallelcluster-common/attributes/common_ubuntu.rb
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_common.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_install_debian.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_install_rhel.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-shared/attributes/environment.rb
  kitchen.resources-config.yml
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_config/nvidia_spec.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2201 Move nvidia_dcgm resource to platform cookbook
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_ubuntu.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/partial/_nvidia_dcgm_alinux2_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/partial/_nvidia_dcgm_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_dcgm_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_dcgm_spec.rb
  kitchen.resources-install.yml
  test/resources/controls/aws_parallelcluster_install/nvidia_spec.rb
Labels: skip-changelog-update, 3.x

#2205 Move nvidia recipe from install to platform cookbook
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/recipes/install/nvidia.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2207 Move install_packages resource to platform cookbook
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu22.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/install_packages_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/partial/_install_packages_debian.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/partial/_install_packages_rhel_amazon.rb
  cookbooks/aws-parallelcluster-install/spec/unit/resources/install_packages_spec.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu18.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu20.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu22.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_common.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_debian.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_rhel_amazon.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/install_packages_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/install_packages_spec.rb
  kitchen.resources-install.yml
Labels: skip-changelog-update, 3.x, skip-system-tests

#2210 [Isolated Regions] Remove security updates from script used to configure ISO instances
  cookbooks/aws-parallelcluster-install/templates/default/base/patch-iso-instance.sh.erb
Labels: skip-changelog-update, 3.x

#2211 Move log_rotation recipe from init to config phase
  cookbooks/aws-parallelcluster-config/recipes/config.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
Labels: skip-changelog-update, 3.x

#2214 [develop] Save cuda_samples_version into node_attributes
  cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/cuda_spec.rb
Labels: skip-changelog-update

#2213 [develop] Remove tag:config from system_authentication kitchen tests
  cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb
Labels: skip-changelog-update

#2217 [develop] Rename group used to read SLURM_RESUME_FILE
  cookbooks/aws-parallelcluster-shared/attributes/users.rb
  test/recipes/controls/aws_parallelcluster_slurm/install_slurm_spec.rb
Labels: skip-changelog-update

#2220 [develop] Rename group used to read SLURM_RESUME_FILE
  cookbooks/aws-parallelcluster-shared/attributes/users.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/resume_program.erb
Labels: skip-changelog-update

#2222 Transform intel_hpc in a resource in platform cookbook
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/recipes/intel.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/recipes/intel_hpc.rb
  cookbooks/aws-parallelcluster-platform/files/centos-7/intel/intelpython2_modulefile
  cookbooks/aws-parallelcluster-platform/files/centos-7/intel/intelpython3_modulefile
  cookbooks/aws-parallelcluster-platform/files/env2
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/create_modulefile.rb
  cookbooks/aws-parallelcluster-platform/resources/intel_hpc/intel_hpc.rb
  cookbooks/aws-parallelcluster-platform/resources/intel_hpc/intel_hpc_centos7.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/intel_hpc_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/intel_hpc_spec.rb
  cookbooks/aws-parallelcluster-shared/attributes/intel.rb
  kitchen.recipes-config.yml
  kitchen.recipes-install.yml
  test/recipes/controls/aws_parallelcluster_install/intel_hpc_spec.rb
Labels: skip-changelog-update, 3.x

#2224 Create os_type resource
  cookbooks/aws-parallelcluster-shared/resources/os_type/os_type_alinux2.rb
  cookbooks/aws-parallelcluster-shared/resources/os_type/os_type_centos7.rb
  cookbooks/aws-parallelcluster-shared/resources/os_type/os_type_redhat8.rb
  cookbooks/aws-parallelcluster-shared/resources/os_type/os_type_ubuntu.rb
  cookbooks/aws-parallelcluster-shared/resources/os_type/partial/_os_type_common.rb
  cookbooks/aws-parallelcluster-shared/spec/unit/resources/os_type_spec.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2227 Remove mariadb-libs from Intel HPC deps
  cookbooks/aws-parallelcluster-platform/resources/intel_hpc/intel_hpc_centos7.rb
  cookbooks/aws-parallelcluster-platform/test/controls/intel_hpc_spec.rb
Labels: skip-changelog-update

#2228 Add graphic_instance condition to dcv_gpu_accel_supported function
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/dcv_spec.rb
Labels: skip-changelog-update, skip-system-tests

#2230 Avoid stepping into the cookbook to kitchen-test it
  Berksfile
  cookbooks/aws-parallelcluster-awsbatch/kitchen.awsbatch-install.yml
  cookbooks/aws-parallelcluster-awsbatch/test/inspec.yml
  cookbooks/aws-parallelcluster-computefleet/Berksfile
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-install.yml
  cookbooks/aws-parallelcluster-computefleet/test/inspec.yml
  cookbooks/aws-parallelcluster-entrypoints/Berksfile
  cookbooks/aws-parallelcluster-entrypoints/kitchen.entrypoints-install.yml
  cookbooks/aws-parallelcluster-entrypoints/test/inspec.yml
  cookbooks/aws-parallelcluster-environment/Berksfile
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/test/inspec.yml
  cookbooks/aws-parallelcluster-platform/Berksfile
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/test/inspec.yml
  cookbooks/aws-parallelcluster-shared/Berksfile
  cookbooks/aws-parallelcluster-shared/kitchen.shared-config.yml
  cookbooks/aws-parallelcluster-shared/kitchen.shared-install.yml
  cookbooks/aws-parallelcluster-shared/test/inspec.yml
  cookbooks/aws-parallelcluster-slurm/Berksfile
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-install.yml
  cookbooks/aws-parallelcluster-slurm/test/inspec.yml
  kitchen.ec2.sh
  kitchen.local-yml.sh
  kitchen.recipes-install.yml
Labels: skip-changelog-update, 3.x

#2233 Use test_resource resource in test_resource recipe
  cookbooks/aws-parallelcluster-tests/recipes/test_resource.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2235 Move networking recipe to platform cookbook
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/recipes/config/networking.rb
  cookbooks/aws-parallelcluster-platform/test/controls/networking_spec.rb
  kitchen.recipes-config.yml
Labels: skip-changelog-update, skip-system-tests
