Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-03, with the labels that each got.

#1822 Use a custom NetworkManager.conf with the correct dhcp plugin in Red Hat 8
  cookbooks/aws-parallelcluster-slurm/files/redhat/dns_domain/NetworkManager.conf
  cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_redhat8.rb
  test/resources/controls/aws_parallelcluster_slurm/dns_domain_spec.rb
Labels: skip-changelog-update

#1819 Skip cookbooks for functionality currently unsupported in RHEL8
  cookbooks/aws-parallelcluster-install/recipes/install.rb
Labels: skip-changelog-update, 3.x

#1823 [Isolated Regions] Improvements to '/opt/parallelcluster/scripts/patch-iso-instance.sh'.
  cookbooks/aws-parallelcluster-install/recipes/base_isolated.rb
  cookbooks/aws-parallelcluster-install/templates/default/base/patch-iso-instance.sh.erb
Labels: skip-changelog-update, 3.x

#1808 Use start of string anchor regex for dir path ref
  cookbooks/aws-parallelcluster-config/resources/manage_ebs.rb
Labels: skip-changelog-update

#1824 [Multi User] Add support for AD password as SSM Parameter.
  cookbooks/aws-parallelcluster-config/recipes/directory_service.rb
  cookbooks/aws-parallelcluster-config/templates/default/directory_service/update_directory_service_password.sh.erb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1826 Allow cluster admin user to run sinfo command as root
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/99-parallelcluster-slurm.erb
Labels: skip-changelog-update, 3.x

#1827 Use nfs third party cookbook for RHEL8
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/nfs_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/partial/_configure.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/partial/_install_nfs4_and_disable.rb
  cookbooks/aws-parallelcluster-common/resources/nfs/partial/_install_nfs_debian.rb
  cookbooks/aws-parallelcluster-common/templates/default/nfs/nfs.conf.erb
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/recipes/nfs.rb
  kitchen.recipes.yml
  kitchen.resources.yml
  test/recipes/controls/aws_parallelcluster_config/nfs_spec.rb
  test/resources/controls/aws_parallelcluster_config/nfs_spec.rb
Labels: skip-changelog-update, 3.x

#1828 Add dependency on nfs cookbook
  cookbooks/aws-parallelcluster-common/Berksfile
  cookbooks/aws-parallelcluster-common/metadata.rb
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
Labels: skip-changelog-update

#1829 remove conditioning on scheduler = awsbatch for fetch_config execution
  cookbooks/aws-parallelcluster-config/recipes/config.rb
  cookbooks/aws-parallelcluster-config/recipes/finalize.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-config/recipes/update.rb
Labels: skip-changelog-update, 3.x

#1831 Remove os_properties from root cookbook
  test/common/inspec.yml
  test/common/libraries/os_properties.rb
  test/recipes/inspec.yml
  test/resources/inspec.yml
Labels: skip-changelog-update, 3.x

#1832 Test for find_centos_minor_version
  cookbooks/aws-parallelcluster-common/resources/lustre/lustre_centos7.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_setup_spec.rb
Labels: skip-changelog-update, 3.x

#1833 [Multi User] Fix regression impacting the retrieval of PasswordSecretArn when it is expressed as a secrets in Secrets Manager.
  cookbooks/aws-parallelcluster-config/recipes/directory_service.rb
Labels: bug, skip-changelog-update, 3.x

#1834 Test lustre mount and unmount
  cookbooks/aws-parallelcluster-common/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_mount_spec.rb
Labels: skip-changelog-update, 3.x

#1835 Refactor and simplify lustre mount/unmount code
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-common/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_mount_spec.rb
Labels: skip-changelog-update, 3.x

#1836 Move package_repos kitchen test to aws-parallelcluster-common
  .github/workflows/dokken-unit-tests.yml
  cookbooks/aws-parallelcluster-common/kitchen.resources.yml
  cookbooks/aws-parallelcluster-common/test/resources/controls/package_repos_spec.rb
  kitchen.resources.yml
Labels: skip-changelog-update, 3.x

#1837 Rename nfs-threads into nfs-configured
  .github/workflows/dokken-unit-tests.yml
Labels: skip-changelog-update, 3.x

#1838 Add ChefSpec test for efs:install_utils
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_build_install_efs_utils_centos_redhat.rb
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_check_version.rb
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_install_utils_debian.rb
  cookbooks/aws-parallelcluster-common/resources/partial/_get_package_version.rb
  cookbooks/aws-parallelcluster-common/resources/partial/_get_package_version_dpkg.rb
  cookbooks/aws-parallelcluster-common/resources/partial/_get_package_version_rpm.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  kitchen.resources.yml
Labels: skip-changelog-update, 3.x

#1840 Add ChefSpec tests for efs mount/unmount
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efs_spec.rb
Labels: skip-changelog-update, 3.x

#1842 Add ChefSpec tests for package_repos
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/package_repos_spec.rb
Labels: skip-changelog-update, 3.x

#1843 Add ChefSpec tests for nfs
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/nfs_spec.rb
Labels: skip-changelog-update, 3.x

#1845 Add ChefSpec tests for c_states
  cookbooks/aws-parallelcluster-install/spec/unit/resources/c_states_spec.rb
Labels: skip-changelog-update, 3.x

#1846 Add ChefSpec tests for c_states on arm
  cookbooks/aws-parallelcluster-install/spec/unit/resources/c_states_spec.rb
Labels: skip-changelog-update, 3.x

#1847 Refactor c_states
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_amazon2.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_centos7.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/c_states_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/partial/_c_states_common.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/partial/_c_states_debian.rb
  cookbooks/aws-parallelcluster-install/resources/c_states/partial/_c_states_redhat_based.rb
Labels: skip-changelog-update, 3.x

#1849 Fix linting error R1710
  cookbooks/aws-parallelcluster-config/files/default/dcv/pcluster_dcv_authenticator.py
Labels: skip-changelog-update, 3.x

#1848 Add ChefSpec tests for ec2_udev_rules
  cookbooks/aws-parallelcluster-install/spec/unit/resources/ec2_udev_rules_spec.rb
Labels: skip-changelog-update, 3.x

#1850 Add ChefSpec tests for install_packages
  cookbooks/aws-parallelcluster-install/spec/unit/resources/install_packages_spec.rb
Labels: skip-changelog-update, 3.x

#1851 Add ChefSpec tests for mysql_client
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_download_and_install.rb
  cookbooks/aws-parallelcluster-install/spec/unit/resources/mysql_client_spec.rb
Labels: skip-changelog-update, 3.x

#1853 Optimize ChefSpec
  cookbooks/aws-parallelcluster-common/spec/unit/recipes/setup_envars_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efa_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/lustre_setup_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/network_service_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/nfs_spec.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/package_repos_spec.rb
  cookbooks/aws-parallelcluster-config/spec/unit/recipes/chrony_spec.rb
  cookbooks/aws-parallelcluster-install/spec/unit/recipes/ami_cleanup_spec.rb
Labels: skip-changelog-update, 3.x

#1854 Refactor ChefSpec test for efa
  cookbooks/aws-parallelcluster-common/resources/efa/efa_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/efa/partial/_setup.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efa_spec.rb
Labels: skip-changelog-update, 3.x

#1866 Fix tj-actions/changed-files patch version
  .github/workflows/dokken-validate.yml
  .github/workflows/system-tests-centos7.yml
  .github/workflows/system-tests-ubuntu.yml
Labels: skip-changelog-update, 3.x

#1856 [develop] Add tests to verify pam_slurm_adopt module installation
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_slurm/install_slurm_spec.rb
Labels: skip-changelog-update, 3.x

#1868 Move `format_directory` function to common cookbook
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1870 Fix network interface configuration for rhel8
  cookbooks/aws-parallelcluster-config/files/redhat-8/network_interfaces/configure_nw_interface.sh
Labels: skip-changelog-update, 3.x

#1871 Add template to configure setup-ephemeral.service in order to wait after network-online.target for redhat8
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_amazon2.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_centos7.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/ephemeral_drives_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/resources/ephemeral_drivers/partial/_ephemeral_drives_common.rb
  cookbooks/aws-parallelcluster-install/templates/default/base/setup-ephemeral.service.erb
  kitchen.recipes.yml
  kitchen.resources.yml
  kitchen.validate.yml
  test/resources/controls/aws_parallelcluster_install/ephemeral_drives_spec.rb
Labels: skip-changelog-update

#1873 [Versioning] Update CHANGELOG for release 3.5.1.
  CHANGELOG.md
Labels: 3.x

#1877 [Code Quality] Fix linter error R1710 in DCV Authenticator.
  cookbooks/aws-parallelcluster-config/files/default/dcv/pcluster_dcv_authenticator.py
Labels: skip-changelog-update, 3.x

#1874 tox codecov + report upload in ci
  .github/workflows/ci.yml
  .gitignore
  README.md
  cookbooks/aws-parallelcluster-install/files/default/cloudwatch_agent/verify_cloudwatch_agent_public_key_fingerprint.py
  tox.ini
Labels: skip-changelog-update, dependencies, 3.x

#1878 [Isolated Regions] Setting AWS CLI system-wide environment variables within the 'patch-iso-instance' script: AWS_DEFAULT_REGION and AWS_CA_BUNDLE.
  cookbooks/aws-parallelcluster-install/templates/default/base/patch-iso-instance.sh.erb
Labels: skip-changelog-update, 3.x

#1882 Upgrade EFA installer from 1.21.0 to 1.22.0
  CHANGELOG.md
  attributes/default.rb
Labels: skip-changelog-update

#1884 [Versioning] Update changelog for 3.5.1.
  CHANGELOG.md
Labels: 3.x

#1883 Execute nmcli write commands with sudo privileges
  cookbooks/aws-parallelcluster-config/files/redhat-8/network_interfaces/configure_nw_interface.sh
Labels: skip-changelog-update, 3.x

#1863 3.x Publish JSON event logs to CloudWatch
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-config/files/default/cloudwatch_agent/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_slurm_resume.conf.erb
Labels: skip-changelog-update, 3.x

#1887 [3.x] Move installation of hostname package into dns_domain setup action, called from install cookbook
  cookbooks/aws-parallelcluster-common/resources/dns_domain/dns_domain.rb
  cookbooks/aws-parallelcluster-common/resources/dns_domain/dns_domain_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/dns_domain/partial/_dns_search_domain_redhat.rb
  cookbooks/aws-parallelcluster-common/resources/dns_domain/partial/_dns_search_domain_ubuntu.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/partial/_install_packages_debian.rb
  cookbooks/aws-parallelcluster-install/resources/install_packages/partial/_install_packages_rhel_amazon.rb
  cookbooks/aws-parallelcluster-slurm/recipes/init_dns.rb
  kitchen.recipes.yml
  kitchen.resources.yml
  test/recipes/controls/aws_parallelcluster_slurm/init_dns_spec.rb
  test/resources/controls/aws_parallelcluster_install/install_packages_spec.rb
  test/resources/controls/aws_parallelcluster_slurm/dns_domain_spec.rb
Labels: skip-changelog-update

#1896 Create volume resource
  cookbooks/aws-parallelcluster-config/resources/volume/volume.rb
  cookbooks/aws-parallelcluster-config/spec/unit/resources/volume_spec.rb
Labels: skip-changelog-update, 3.x

#1897 Split kitchen tests into install and config
  .github/workflows/dokken-unit-tests.yml
  .github/workflows/dokken-validate.yml
  kitchen.ec2.sh
  kitchen.ec2.yml
  kitchen.recipes-config.yml
  kitchen.recipes-install.yml
  kitchen.resources-config.yml
  kitchen.resources-install.yml
  kitchen.validate-install.yml
Labels: skip-changelog-update, 3.x

#1899 Prepare kitchen configuration to be used by kitchen tests running on Jenkins
  kitchen.ec2.sh
  kitchen.ec2.yml
  kitchen.jenkins.yml
Labels: skip-changelog-update, 3.x

#1903 Allow awsbatch-related kitchen tests to fetch from s3
  kitchen.jenkins.yml
Labels: skip-changelog-update, 3.x

#1895 fetch_and_run in python supporting multiple custom actions
  .dockerignore
  cookbooks/aws-parallelcluster-config/files/default/custom_action_executor/custom_action_executor.py
  cookbooks/aws-parallelcluster-config/recipes/custom_actions_setup.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-config/templates/default/init/cfnconfig.erb
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  system_tests/Dockerfile.centos7
  system_tests/Dockerfile.ubuntu
  system_tests/cluster-config.yaml
  test/unit/custom_action_executor/test_custom_action_executor.py
  tox.ini
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#1904 Transform node_attributes to a common recipe
  cookbooks/aws-parallelcluster-common/recipes/node_attributes.rb
  cookbooks/aws-parallelcluster-common/spec/unit/recipes/node_attributes_spec.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
Labels: skip-changelog-update, 3.x

#1906 Set node['cluster']['base_os'] in kitchen.ec2.yml
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#1907 Refactor kitchen config file for Jenkins
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x

#1909 Don't look for VPC_ID if already defined
  kitchen.ec2.sh
Labels: skip-changelog-update, 3.x

#1908 Avoid interacting with S3 and DDB in kitchen tests
  cookbooks/aws-parallelcluster-common/libraries/cluster_config.rb
  cookbooks/aws-parallelcluster-common/libraries/kitchen.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_fleet_status.rb
  cookbooks/aws-parallelcluster-config/resources/fetch_config.rb
  cookbooks/aws-parallelcluster-config/spec/unit/resources/fetch_config_spec.rb
  kitchen.global.yml
  libraries/helpers.rb
  test/data/cluster-config.yml
  test/data/instance-types-data.json
Labels: skip-changelog-update, 3.x

#1910 Fix imds_spec
  kitchen.recipes-config.yml
  test/recipes/controls/aws_parallelcluster_config/imds_spec.rb
Labels: skip-changelog-update, 3.x

#1911 Start adding InSpec verifications to cluster node kitchen tests
  cookbooks/aws-parallelcluster-common/test/common/libraries/node.rb
  kitchen.validate-config.yml
  test/recipes/controls/validate/openssh_spec.rb
  test/recipes/controls/validate/setup_envars_spec.rb
  test/recipes/controls/validate/setup_users_spec.rb
  test/recipes/controls/validate/slurm_config_spec.rb
Labels: skip-changelog-update, 3.x

#1901 Add log rotation configuration for JSON event logs
  cookbooks/aws-parallelcluster-config/templates/default/log_rotation/parallelcluster_log_rotation.erb
Labels: skip-changelog-update

#1914 document kitchen tests local execution in README
  .ruby-version
  README.md
  kitchen.docker.sh
  kitchen.ec2.sh
Labels: skip-changelog-update, 3.x

#1921 Enable check intel mpi version for redhat8
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update

#1924 Rename t:config to tag:config
  cookbooks/aws-parallelcluster-common/test/recipes/controls/setup_envars_spec.rb
  kitchen.validate-config.yml
  test/recipes/controls/aws_parallelcluster_config/dcv_spec.rb
  test/recipes/controls/aws_parallelcluster_install/users_spec.rb
  test/recipes/controls/aws_parallelcluster_slurm/slurm_users_spec.rb
Labels: skip-changelog-update, 3.x

#1925 Move tests test_processes.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/test_processes.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_install/supervisord_spec.rb
  test/recipes/controls/aws_parallelcluster_slurm/slurm_processes_spec.rb
Labels: skip-changelog-update, 3.x

#1926 Move tests test_imds.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/test_imds.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_config/imds_spec.rb
Labels: skip-changelog-update, 3.x

#1929 Move tests from test_nvidia.rb recipe to InSpec
  cookbooks/aws-parallelcluster-common/test/common/libraries/instance.rb
  cookbooks/aws-parallelcluster-common/test/common/libraries/os_properties.rb
  cookbooks/aws-parallelcluster-test/recipes/test_nvidia.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_config/nvidia_spec.rb
Labels: skip-changelog-update, 3.x

#1930 Move tests from test_dcv.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/test_dcv.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_config/dcv_spec.rb
Labels: skip-changelog-update, 3.x

#1932 Move chrony tests from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_config/chrony_spec.rb
Labels: skip-changelog-update, 3.x

#1936 Move nfs tests from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/resources/controls/aws_parallelcluster_config/nfs_spec.rb
Labels: skip-changelog-update, 3.x

#1933 Move dcv tests from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_config/dcv_spec.rb
Labels: skip-changelog-update, 3.x

#1938 Move supervisord and ec2blkdev services tests from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/recipes/controls/aws_parallelcluster_install/supervisord_spec.rb
  test/resources/controls/aws_parallelcluster_install/ec2_udev_rules_spec.rb
Labels: skip-changelog-update, 3.x

#1939 Move c_states tests from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/resources/controls/aws_parallelcluster_install/c_states_spec.rb
Labels: skip-changelog-update, 3.x

#1934 Move intel mpi tests from tests.rb recipe to InSpec
  attributes/default.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  kitchen.recipes-install.yml
  kitchen.validate-install.yml
  test/recipes/controls/aws_parallelcluster_install/intel_mpi_spec.rb
Labels: skip-changelog-update, 3.x

#1937 Move ulimit test from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_install/users_spec.rb
Labels: skip-changelog-update, 3.x

#1940 Move tests for disabled services from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  kitchen.recipes-install.yml
  kitchen.validate-install.yml
  test/recipes/controls/aws_parallelcluster_install/disable_services_spec.rb
Labels: skip-changelog-update, 3.x

#1941 Move tests for gc_thresh from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_install/gc_thresh_values_spec.rb
Labels: skip-changelog-update, 3.x

#1946 Move awsbatch tests from tests.rb recipe to InSpec
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
  test/recipes/controls/aws_parallelcluster_awsbatch/awsbatch_spec.rb
Labels: skip-changelog-update

#1945 Delete obsolete kitchen config files
  .kitchen.cloud.yml
  .kitchen.yml
  kitchen.jenkins.yml
  kitchen.multinic.yml
Labels: skip-changelog-update

#1950 Create new resource to manage system authentication
  cookbooks/aws-parallelcluster-common/resources/system_authentication/partial/_system_authentication_alinux_centos.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/partial/_system_authentication_common.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/partial/_system_authentication_debian.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_ubuntu18.rb
  cookbooks/aws-parallelcluster-common/resources/system_authentication/system_authentication_ubuntu20.rb
  cookbooks/aws-parallelcluster-config/recipes/directory_service.rb
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  kitchen.resources-config.yml
  kitchen.resources-install.yml
  kitchen.validate-install.yml
  test/resources/controls/aws_parallelcluster_config/system_authentication_spec.rb
Labels: skip-changelog-update

#1951 Fix efa_supported conditions
  cookbooks/aws-parallelcluster-common/test/common/libraries/instance.rb
Labels: skip-changelog-update

#1943 3.x Add error event reporting to custom compute actions
  cookbooks/aws-parallelcluster-config/files/default/custom_action_executor/custom_action_executor.py
  cookbooks/aws-parallelcluster-config/recipes/custom_actions_setup.rb
  cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
  cookbooks/aws-parallelcluster-slurm/libraries/emit_chef_error_event.rb
  test/unit/custom_action_executor/test_custom_action_executor.py
  tox.ini
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#1954 minversion for tox
  tox.ini
Labels: skip-changelog-update, 3.x

#1957 3.x Fix failing integration tests
  cookbooks/aws-parallelcluster-config/files/default/custom_action_executor/custom_action_executor.py
  test/unit/custom_action_executor/test_custom_action_executor.py
Labels: skip-changelog-update, 3.x

#1955 [develop] Refactor code for slurm configs to prepare it for custom slurm settings
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/common/slurm_parallelcluster_utils.conf
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster_queue_gres.conf
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster_queue_partition.conf
Labels: skip-changelog-update, 3.x

#1961 [3.x] Upgrade EFA to 1.22.1
  CHANGELOG.md
  attributes/default.rb
Labels: skip-changelog-update

#1958 Render CustomSlurmSettings in cookbook
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_custom_slurm_settings_include_file_generator.py
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
  libraries/helpers.rb
  test/unit/slurm/test_custom_slurm_settings_include_file_generator.py
  test/unit/slurm/test_custom_slurm_settings_include_file_generator/test_generate_custom_slurm_settings_include_files/expected_outputs/pcluster/custom_slurm_settings_include_file_slurm.conf
  test/unit/slurm/test_custom_slurm_settings_include_file_generator/test_generate_custom_slurm_settings_include_files/sample_input.yaml
  test/unit/slurm/test_custom_slurm_settings_include_file_generator/test_generate_empty_custom_slurm_settings_include_files/expected_outputs/pcluster/custom_slurm_settings_include_file_slurm.conf
  test/unit/slurm/test_custom_slurm_settings_include_file_generator/test_generate_empty_custom_slurm_settings_include_files/sample_input.yaml
  test/unit/slurm/test_slurm_config_generator.py
Labels: 3.x

#1968 Fix linters
  cookbooks/aws-parallelcluster-install/resources/gdrcopy/partial/_gdrcopy_common.rb
  test/resources/controls/aws_parallelcluster_install/nvidia_spec.rb
Labels: skip-changelog-update
