Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-02, with the labels that each got.

#1707 Set METADATA_REQUEST_TIMEOUT in the manageVolume and ec2_dev_2_volid scripts
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/common.py
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/manageVolume.py
Labels: skip-changelog-update

#1711 Move gc_threshold configuration into a new recipe and add tests
  attributes/default.rb
  cookbooks/aws-parallelcluster-install/attributes/default.rb
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/gc_thresh_values.rb
  kitchen.recipes.yml
  libraries/helpers.rb
  test/recipes/controls/aws_parallelcluster_install/gc_thresh_values_spec.rb
Labels: skip-changelog-update

#1715 Revert "Convert EFA installation recipe into a resource"
  cookbooks/aws-parallelcluster-install/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/efa.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-install/resources/efa/efa.rb
  kitchen.resources.yml
  kitchen.validate.yml
  libraries/helpers.rb
  test/resources/controls/aws_parallelcluster_install/efa_spec.rb
Labels: skip-changelog-update

#1717 Enable additional Slurm logging for the Power Saving plugin
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update, 3.x

#1721 New entry in CHANGELOG for increased verbosity in Slurm logs
  CHANGELOG.md
Labels: 3.x

#1716 Add cfnconfig_mixed recipe and tests
  cookbooks/aws-parallelcluster-config/recipes/cfnconfig_mixed.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/cfnconfig_mixed_spec.rb
Labels: skip-changelog-update

#1713 Test selinux with RedHat 8
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/disable_selinux.rb
  kitchen.recipes.yml
  test/common/libraries/os_properties.rb
  test/recipes/controls/aws_parallelcluster_install/disable_selinux_spec.rb
Labels: skip-changelog-update

#1708 Add test for disabled services
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/disable_services.rb
  kitchen.recipes.yml
  test/common/libraries/os_properties.rb
  test/recipes/controls/aws_parallelcluster_install/disable_services_spec.rb
Labels: skip-changelog-update, 3.x

#1642 Allow the installation of Slurm from any commit in the Slurm GitHub project
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1727 Move sticky_bits logic into a new resource
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/recipes/test_resource.rb
  cookbooks/aws-parallelcluster-config/resources/sticky_bits/sticky_bits.rb
  cookbooks/aws-parallelcluster-config/resources/sticky_bits/sticky_bits_ubuntu2004.rb
  kitchen.resources.yml
  test/common/libraries/os_properties.rb
  test/resources/controls/aws_parallelcluster_config/sticky_bits_spec.rb
Labels: skip-changelog-update

#1735 Move CW Agent config test to correct folder
  test/recipes/controls/aws_parallelcluster_config/cloudwatch_agent_spec.rb
Labels: skip-changelog-update, 3.x

#1737 Wip/cw agent test
  kitchen.recipes.yml
Labels: skip-changelog-update, 3.x

#1729 [bandit] Use absolute path for program called in subprocess call
  cookbooks/aws-parallelcluster-config/files/default/dcv/pcluster_dcv_authenticator.py
Labels: skip-changelog-update, skip-security-exclusions-check

#1710 [RHEL8][Slurm] Isolate mysql attributes
  attributes/default.rb
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/mysql_client.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/mysql_client_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_download_and_install.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_package_properties.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_source_link.rb
  cookbooks/aws-parallelcluster-install/resources/mysql_client/partial/_validate.rb
  cookbooks/aws-parallelcluster-test/libraries/helpers.rb
  cookbooks/aws-parallelcluster-test/recipes/validate_mysql.rb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1741 [RHEL8][Slurm] Add Tests to Install-Pmix recipe
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_pmix.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_slurm/install_pmix_spec.rb
Labels: skip-changelog-update, 3.x

#1743 Define new fs_update recipe and add tests for it
  cookbooks/aws-parallelcluster-config/recipes/fs_update.rb
  cookbooks/aws-parallelcluster-config/recipes/head_node_base.rb
  cookbooks/aws-parallelcluster-config/recipes/update.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/fs_update_spec.rb
Labels: skip-changelog-update

#1736 Add sudo configuration test
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/recipes/sudo.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/sudo_spec.rb
Labels: skip-changelog-update, 3.x

#1745 Test set of number of nfs threads
  cookbooks/aws-parallelcluster-config/recipes/nfs.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/nfs_spec.rb
Labels: skip-changelog-update

#1749 Add slurm dependency
  cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies.rb
  cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_redhat8.rb
  test/resources/controls/aws_parallelcluster_slurm/slurm_dependencies_spec.rb
Labels: skip-changelog-update, 3.x

#1750 Add test for install_jwt recipe
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_jwt.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_slurm/install_jwt_spec.rb
Labels: skip-changelog-update, 3.x

#1740 [bandit] Validate args before subprocess calls
  cookbooks/aws-parallelcluster-install/files/default/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/manageVolume.py
  test/unit/ec2_udev_rules/test_ec2_dev_2_volid.py
  test/unit/ec2_udev_rules/test_manage_volume.py
  tox.ini
Labels: skip-changelog-update, 3.x

#1746 Add test for chrony configuration
  cookbooks/aws-parallelcluster-config/recipes/chrony.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/chrony_spec.rb
Labels: skip-changelog-update, 3.x

#1756 Add test of mount_share recipe
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-config/recipes/mount_shared.rb
  cookbooks/aws-parallelcluster-test/recipes/export_directories_mock.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/mount_shared_spec.rb
Labels: skip-changelog-update

#1723 Split environment preparation steps in Ubuntu system tests
  system_tests/Dockerfile.ubuntu
Labels: skip-changelog-update, 3.x

#1758 Add test for install_packages resource
  kitchen.resources.yml
Labels: skip-changelog-update, 3.x

#1748 Update pre-commit config
  .pre-commit-config.yaml
Labels: skip-changelog-update, 3.x

#1766 Add test for ephemeral drives setup
  cookbooks/aws-parallelcluster-install/recipes/ephemeral_drives.rb
  cookbooks/aws-parallelcluster-test/recipes/cfnconfig_mock.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/ephemeral_drives_spec.rb
Labels: skip-changelog-update

#1753 Transform install_munge recipe into a resource
  attributes/default.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install_munge.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge/munge.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge/munge_redhat8.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge/partial/_munge_actions.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/munge/munge-init.erb
  kitchen.resources.yml
  test/resources/controls/aws_parallelcluster_slurm/munge_spec.rb
Labels: skip-changelog-update, 3.x

#1769 Skip unsupported install recipes when building RHEL8 images
  cookbooks/aws-parallelcluster-awsbatch/recipes/install.rb
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-install/recipes/dcv.rb
  cookbooks/aws-parallelcluster-install/recipes/efs.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/recipes/install.rb
Labels: skip-changelog-update

#1755 Add test for stunnel installation
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/recipes/efs.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/partial/_setup.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/stunnel_amazon2.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/stunnel_centos7.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/stunnel_redhat8.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/stunnel_ubuntu1804.rb
  cookbooks/aws-parallelcluster-install/resources/stunnel/stunnel_ubuntu2004.rb
  kitchen.resources.yml
  test/resources/controls/aws_parallelcluster_install/stunnel_spec.rb
Labels: skip-changelog-update, 3.x

#1776 Add ARM PL value for RedHat OS
  attributes/default.rb
Labels: skip-changelog-update

#1777 Remove environment-modules and lvm2 packages from base_packages list
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  kitchen.recipes.yml
  kitchen.validate.yml
  system_tests/Dockerfile.centos7
  system_tests/Dockerfile.ubuntu
  test/recipes/controls/aws_parallelcluster_install/ephemeral_drives_spec.rb
  test/resources/controls/aws_parallelcluster_install/install_packages_spec.rb
Labels: skip-changelog-update

#1779 Run kitchen unit tests in separate jobs
  .github/workflows/ci.yml
  .github/workflows/dokken-unit-tests.yml
  .github/workflows/dokken-validate.yml
Labels: skip-changelog-update, 3.x

#1775 Add IMDS test
  cookbooks/aws-parallelcluster-config/recipes/imds.rb
  cookbooks/aws-parallelcluster-config/recipes/init.rb
  cookbooks/aws-parallelcluster-install/attributes/default_amazon2.rb
  cookbooks/aws-parallelcluster-install/attributes/default_centos7.rb
  cookbooks/aws-parallelcluster-install/attributes/default_redhat8.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu18.rb
  cookbooks/aws-parallelcluster-install/attributes/default_ubuntu20.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/imds_spec.rb
Labels: skip-changelog-update, 3.x

#1783 Add infrastructure to apply patches to a Slurm tarball
  cookbooks/aws-parallelcluster-slurm/files/default/install_slurm/slurm_patches/README.md
  cookbooks/aws-parallelcluster-slurm/recipes/install_slurm.rb
Labels: skip-changelog-update, 3.x

#1785 Merge manage_efs in efs resource
  cookbooks/aws-parallelcluster-common/resources/efs/efs_alinux2.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_centos7.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu1804.rb
  cookbooks/aws-parallelcluster-common/resources/efs/efs_ubuntu2004.rb
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_build_install_efs_utils_centos_redhat.rb
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_build_install_efs_utils_debian.rb
  cookbooks/aws-parallelcluster-common/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-config/recipes/fs_mount.rb
  cookbooks/aws-parallelcluster-config/recipes/update_shared_storages.rb
Labels: skip-changelog-update

#1787 Update GitHub actions
  .github/workflows/changelog_enforcer.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/system-tests-centos7.yml
  .github/workflows/system-tests-ubuntu.yml
Labels: skip-changelog-update

#1786 Moves into slurm cookbook functions used only by slurm recipes
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1793 Add test for compute base
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-config/recipes/compute_base.rb
  cookbooks/aws-parallelcluster-test/recipes/compute_base_mock.rb
  kitchen.recipes.yml
  test/recipes/controls/aws_parallelcluster_config/compute_base_spec.rb
Labels: skip-changelog-update, 3.x

#1796 [Versioning] Bump version to 3.5.1.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-common/metadata.rb
  cookbooks/aws-parallelcluster-config/metadata.rb
  cookbooks/aws-parallelcluster-install/metadata.rb
  cookbooks/aws-parallelcluster-scheduler-plugin/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-test/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: 3.x

#1797 First stab at ChefSpec unit tests
  .github/workflows/ci.yml
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-common/spec/unit/recipes/setup_envars_spec.rb
Labels: skip-changelog-update, 3.x

#1802 ChefSpec test for efa resource
  cookbooks/aws-parallelcluster-common/libraries/helpers.rb
  cookbooks/aws-parallelcluster-common/libraries/networking.rb
  cookbooks/aws-parallelcluster-common/resources/efa/partial/_setup.rb
  cookbooks/aws-parallelcluster-common/resources/package_repos/package_repos.rb
  cookbooks/aws-parallelcluster-common/resources/package_repos/package_repos_redhat8.rb
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efa_spec.rb
Labels: skip-changelog-update, 3.x

#1800 [Isolated Regions] Add support for US isolated regions: us-iso-* and us-isob-*.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-config/resources/manage_fsx.rb
  cookbooks/aws-parallelcluster-config/templates/default/base/parallelcluster_supervisord.conf.erb
  cookbooks/aws-parallelcluster-install/files/default/base/patch-iso-instance.sh
  cookbooks/aws-parallelcluster-install/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-install/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/base_isolated.rb
  libraries/helpers.rb
  system_tests/install_cinc.sh
  util/cinc-install.sh
Labels: 3.x

#1768 Add missing cfn-init log for headnode logrotate config
  cookbooks/aws-parallelcluster-config/templates/default/log_rotation/parallelcluster_log_rotation.erb
Labels: skip-changelog-update

#1804 Check status of Slurm services after starting them
  cookbooks/aws-parallelcluster-slurm/recipes/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/finalize_compute.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update_head_node.rb
Labels: skip-changelog-update, 3.x

#1806 Fix os validation for RHEL8
  kitchen.docker.yml
  libraries/helpers.rb
Labels: skip-changelog-update, 3.x

#1809 Fix parentheses in github action
  .github/workflows/dokken-unit-tests.yml
Labels: skip-changelog-update

#1805 [3.x] Add EFA error message on RH < 8.4
  cookbooks/aws-parallelcluster-common/attributes/common.rb
  cookbooks/aws-parallelcluster-common/resources/efa/efa_redhat8.rb
  cookbooks/aws-parallelcluster-common/resources/efa/partial/_setup.rb
  cookbooks/aws-parallelcluster-common/spec/unit/resources/efa_spec.rb
Labels: skip-changelog-update

#1812 First stab at ChefSpec tests for aws-parallelcluster-install
  .github/workflows/ci.yml
  cookbooks/aws-parallelcluster-install/Berksfile
  cookbooks/aws-parallelcluster-install/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-install/spec/unit/recipes/ami_cleanup_spec.rb
Labels: skip-changelog-update, 3.x

#1810 Disable NVIDIA on RHEL8
  cookbooks/aws-parallelcluster-config/recipes/base.rb
  cookbooks/aws-parallelcluster-install/recipes/install.rb
  cookbooks/aws-parallelcluster-test/recipes/tests.rb
Labels: skip-changelog-update, 3.x

#1815 Move common ChefSpec code to aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-common/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-install/spec/spec_helper.rb
Labels: skip-changelog-update, 3.x
