Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-07, with the labels that each got.

#2344 Remove PostgreSQL packages
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_redhat8.rb
Labels: skip-changelog-update

#2348 [develop] Replace nvidia-persistenced with parallelcluster_nvidia service
  cookbooks/aws-parallelcluster-platform/libraries/nvidia.rb
  cookbooks/aws-parallelcluster-platform/recipes/config/nvidia_uvm.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/nvidia_spec.rb
  cookbooks/aws-parallelcluster-platform/templates/nvidia/parallelcluster_nvidia_service.erb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_spec.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_slurmd_systemd_service.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/compute/slurmd_nvidia_persistenced.conf.erb
  cookbooks/aws-parallelcluster-slurm/test/controls/config_slurmd_systemd_service_spec.rb
Labels: skip-changelog-update

#2349 Configure partition to run jobs on nodes exclusively allocated based on the JobExclusiveAllocation parameter
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/config_renderer.py
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_with_job_exc_alloc/expected_outputs/pcluster/slurm_parallelcluster_queue_jls_enabled_partition.conf
Labels: skip-changelog-update, 3.x

#2350 Update the keys that are generated by pcluster from RSA keys to ED25519 on the cluster
  cookbooks/aws-parallelcluster-environment/templates/directory_service/generate_ssh_key.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/directory_service_spec.rb
  cookbooks/aws-parallelcluster-platform/recipes/config/cluster_user.rb
Labels: skip-changelog-update, skip-system-tests

#2352 Install libdbus-1-dev to build the slurm cgroups v2 plugin for Ubuntu 2204
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu22.rb
Labels: skip-changelog-update, skip-system-tests

#2351 Update NVIDIA driver to account for what is available from Canonical
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
Labels: skip-system-tests

#2353 Push job info to cw log
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
Labels: skip-changelog-update

#2355 [develop] Export /opt/intel only when it exists.
  cookbooks/aws-parallelcluster-environment/recipes/config/shared_storages.rb
Labels: skip-changelog-update, 3.x

#2362 Update NFS configure to stop the service on compute nodes and the test to check that the service is stopped
  cookbooks/aws-parallelcluster-environment/resources/nfs/partial/_configure.rb
  cookbooks/aws-parallelcluster-environment/test/controls/nfs_spec.rb
Labels: skip-changelog-update

#2361 Add keys management for Login Nodes to avoid MITM warning
  cookbooks/aws-parallelcluster-environment/files/login_nodes/keys-manager.sh
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/login_nodes_keys.rb
  cookbooks/aws-parallelcluster-environment/recipes/init.rb
  cookbooks/aws-parallelcluster-environment/recipes/test/mock_login_node_keys.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/login_nodes_keys_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/login_nodes_keys_spec.rb
Labels: skip-changelog-update, 3.x

#2369 Add Ubuntu 22 checksum for DCV download. Separate Ubuntu 20 and 22 for DCV
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu20.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu22.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_dcv_common.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_ubuntu_common.rb
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
Labels: skip-changelog-update

#2370 Enable DCV installation for Ubuntu 22.04
  cookbooks/aws-parallelcluster-entrypoints/recipes/install.rb
Labels: skip-changelog-update, skip-system-tests

#2374 Fix kitchen test for CloudWatch configuration on head node
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update, 3.x

#2372 Check AD connection and sync user db with remote directory service
  cookbooks/aws-parallelcluster-environment/libraries/directory_service_utils.rb
  cookbooks/aws-parallelcluster-environment/recipes/config/directory_service.rb
Labels: skip-changelog-update, 3.x

#2375 [kitchen tests] Fix GPU health check kitchen tests on Amazon Linux 2 Deep Learning AMI
  cookbooks/aws-parallelcluster-slurm/test/controls/config_health_check_spec.rb
Labels: skip-changelog-update

#2378 Exclude ubuntu 2204 from arm DCV tests as well as ubuntu 2004
  cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb
Labels: skip-changelog-update

#2380 Enable ARM PL install for ubuntu 22
  cookbooks/aws-parallelcluster-platform/recipes/install.rb
Labels: skip-changelog-update

#2381 Add retry to fix sporadic nfs service failure
  cookbooks/aws-parallelcluster-environment/resources/nfs/partial/_configure.rb
Labels: skip-changelog-update, 3.x

#2384 Bump version to 3.7.0b1
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  kitchen.ec2.yml
Labels: skip-changelog-update
