Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-10, with the labels that each got.

#2477 Modify permissions of /etc/sysconfig directory
  cookbooks/aws-parallelcluster-slurm/recipes/finalize/finalize_compute.rb
Labels: skip-changelog-update

#2481 Disable `code-duplication` pylint code-checks
  .pylintrc
  cookbooks/aws-parallelcluster-computefleet/files/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/ec2_dev_2_volid.py
  cookbooks/aws-parallelcluster-environment/files/default/ec2_udev_rules/manageVolume.py
  cookbooks/aws-parallelcluster-platform/test/controls/intel_hpc_spec.rb
  cookbooks/aws-parallelcluster-slurm/files/default/config_slurm/scripts/health_check_manager.py
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  test/unit/clusterstatusmgtd/test_clusterstatusmgtd.py
  test/unit/dcv/test_dcv_authenticator.py
Labels: skip-changelog-update, 3.x

#2454 [develop] Upgrade slurm to 23.02.05 and also PMIx and libjwt
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_jwt.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pmix.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/slurm_spec.rb
Labels: 3.x

#2479 [develop][fix] Add only if condition in the slurm munge key kitchen tests
  cookbooks/aws-parallelcluster-slurm/test/controls/munge_spec.rb
Labels: skip-changelog-update, 3.x

#2478 [Rocky]Update Volume Size for Rocky to be similar to Rhel8
  cookbooks/aws-parallelcluster-platform/resources/fetch_config.rb
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x

#2483 [develop] Move slurm_resume configuration in a sub-recipe
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node_directories.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_slurm_resume.rb
  cookbooks/aws-parallelcluster-slurm/recipes/test/mock_slurm_dir.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/parallelcluster_slurm_resume.conf.erb
  cookbooks/aws-parallelcluster-slurm/test/controls/config_slurm_resume_spec.rb
Labels: skip-changelog-update, 3.x

#2473 [develop] Add a script of checking if there's running LoginNodes inside HeadNode used in munge key rotation script
  cookbooks/aws-parallelcluster-slurm/libraries/update.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_check_login_stopped_script.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/check_login_nodes_stopped.sh.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x

#2492 Disable deprecated flake8-mypy Python tox check
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog-update, 3.x, skip-system-tests

#2493 Disable deprecated flake8-mypy Python tox check
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog-update, 3.x, skip-system-tests

#2495 Upgrade Slurm to version 23.02.6
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: 3.x, skip-system-tests

#2471 [develop] Reuse the rotation script inside the munge resource
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/resources/munge_key_manager.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2487 [develop][fix] Add mock munge key logic in compute setup recipe during kitchen tests
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/recipes/test/mock_munge_key.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2491 [develop] Move MungeKeySecretArn to Scheduling SlurmSettings
  cookbooks/aws-parallelcluster-slurm/kitchen.slurm-config.yml
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/libraries/update.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x, skip-system-tests

#2496 Remove `custom_node_package` from attributes in kitchen tests
  kitchen.validate-config.yml
Labels: skip-changelog-update, 3.x, skip-system-tests

#2497 Upgrade Slurm to version 23.02.6
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: 3.x, skip-system-tests

#2498 Fix missing munge service enablement on head node
  cookbooks/aws-parallelcluster-slurm/resources/munge_key_manager.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2500 Upgrade aws-cfn-bootstrap and Python versions in cookbook
  CHANGELOG.md
  cookbooks/aws-parallelcluster-awsbatch/test/controls/awsbatch_virtualenv_spec.rb
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
Labels: 3.x, skip-system-tests

#2501 Add GitHub action step to free disk space before executing System tests
  .github/workflows/dokken-system-tests.yml
  cookbooks/aws-parallelcluster-awsbatch/recipes/install.rb
Labels: skip-changelog-update

#2502 Bump version to 3.9.0
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2503 Bump version to 3.8.0b1
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x, skip-system-tests

#2514 [Develop] Do not share compute shared dir with login nodes
  cookbooks/aws-parallelcluster-environment/recipes/init/mount_internal_use_efs.rb
Labels: skip-changelog-update

#2513 [Release 3.8] Do not share compute shared dir with login nodes
  cookbooks/aws-parallelcluster-environment/recipes/init/mount_internal_use_efs.rb
Labels: skip-changelog-update

#2511 [develop][fix] Avoid store decoded binary data in bash varibles in rotation script
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x

#2512 [release-3.8][fix] Avoid store decoded binary data in bash varibles in rotation script
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/update_munge_key.sh.erb
Labels: skip-changelog-update, 3.x

#2517 [release-3.8] Using YUM to install Fabric Manager instead of Dnf packages
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_install_rhel.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
Labels: skip-changelog-update, 3.x

#2518 Using YUM to install Fabric Manager instead of Dnf packages
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_install_rhel.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
Labels: skip-changelog-update, 3.x

#2515 [Release 3.8] Add to kitchen test to make sure nodes only have access…
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/test/controls/mount_internal_use_efs_spec.rb
Labels: skip-changelog-update

#2516 [Develop] Add to kitchen test to make sure nodes only have access to …
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/test/controls/mount_internal_use_efs_spec.rb
Labels: skip-changelog-update

#2494 [Spack] Changing the default Spack Root directory from /home to /opt
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config.rb
  cookbooks/aws-parallelcluster-environment/resources/spack/partial/_spack_common.rb
  cookbooks/aws-parallelcluster-environment/test/controls/spack_spec.rb
Labels: skip-changelog-update, 3.x
