Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2023-11, with the labels that each got.

#2523 [Develop] Store the login nodes key mangement script in the dedicated…
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/login_nodes_keys.rb
  cookbooks/aws-parallelcluster-environment/recipes/test/mock_login_node_keys.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/login_nodes_keys_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/login_nodes_keys_spec.rb
Labels: skip-changelog-update

#2522 [Release 3.8] Store the login nodes key mangement script in the dedic…
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config/login_nodes_keys.rb
  cookbooks/aws-parallelcluster-environment/recipes/test/mock_login_node_keys.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/login_nodes_keys_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/login_nodes_keys_spec.rb
Labels: skip-changelog-update

#2524 [develop] Modify the check_login_stopped.sh script to directly use TG name to query
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_check_login_stopped_script.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/libraries/get_target_group_name_spec.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/check_login_nodes_stopped.sh.erb
Labels: skip-changelog-update, 3.x

#2525 [release-3.8] Modify the check_login_stopped.sh script to directly use TG name to query
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_check_login_stopped_script.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/libraries/get_target_group_name_spec.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/check_login_nodes_stopped.sh.erb
Labels: skip-changelog-update, 3.x

#2528 [release-3.8] Increase retries when no dynamoDB entry is found
  cookbooks/aws-parallelcluster-slurm/recipes/init.rb
Labels: skip-changelog-update

#2527 [develop] Increase retries when no dynamoDB entry is found
  cookbooks/aws-parallelcluster-slurm/recipes/init.rb
Labels: skip-changelog-update

#2529 [Release 3.8] Disable Spack until the feature is complete
  cookbooks/aws-parallelcluster-environment/recipes/install.rb
Labels: skip-changelog-update

#2530 [Develop] Disable Spack until the feature is complete
  cookbooks/aws-parallelcluster-environment/recipes/config.rb
  cookbooks/aws-parallelcluster-environment/recipes/install.rb
Labels: skip-changelog-update

#2532 [Release 3.8] Remove Spack InSpec Controls while Spack is disabled
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/test/controls/spack_spec.rb
Labels: skip-changelog-update

#2531 [Develop] Remove Spack InSpec Controls while Spack is disabled
  cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml
  cookbooks/aws-parallelcluster-environment/test/controls/spack_spec.rb
Labels: skip-changelog-update

#2539 Fix bug introduced with DatabaseName functionality
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster_slurmdbd.conf
  test/unit/slurm/test_slurm_config_generator/test_generate_slurm_config_files_slurm_accounting/sample_input_slurm_accounting.yaml
Labels: skip-changelog-update, 3.x

#2535 [release-3.8] Removing Spack Feature from 3.8.0 Changelog
  CHANGELOG.md
Labels: 3.x

#2537 Remove Spack Feature from CHANGELOG.md
  CHANGELOG.md
Labels: 3.x

#2534 Use jinja templating to refactor cloudwatch config to make is easier to add and remove an OS
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_common_utils.py
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config.json
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config_util.py
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2541 [release-3.8][kitchen-test] Fix GPU health check kitchen test on Alinux2 deep learning AMI
  cookbooks/aws-parallelcluster-slurm/test/controls/config_health_check_spec.rb
Labels: bug, skip-changelog-update

#2546 [develop][kitchen-test] Fix GPU health check kitchen test on Alinux2 deep learning AMI
  cookbooks/aws-parallelcluster-slurm/test/controls/config_health_check_spec.rb
Labels: skip-changelog-update

#2543 Patch for use of jinja templating to refactor cloudwatch config
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_common_utils.py
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config_util.py
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/write_cloudwatch_agent_json.py
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2551 [develop] Define inspec test for node-attributes resource
  cookbooks/aws-parallelcluster-shared/kitchen.shared-install.yml
Labels: skip-changelog-update

#2553 Bump version to 3.8.0
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  kitchen.ec2.yml
Labels: skip-changelog-update, 3.x, skip-system-tests

#2555 [release-3.8] Add support of RHEL 8.9
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_rocky8.rb
Labels: skip-changelog-update

#2556 [develop] Specify version 3.2.6 to install for Nvidia DCGM
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/partial/_nvidia_dcgm_common.rb
Labels: skip-changelog-update

#2552 [release-3.8] Specify version 3.2.6 to install for Nvidia DCGM
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/nvidia_dcgm_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/partial/_nvidia_dcgm_common.rb
Labels: skip-changelog-update

#2565 Fix installation of kernel-devel on Rocky 8
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_common.rb
Labels: skip-changelog-update, 3.x

#2561 [Dependencies] Upgrade NVIDIA driver to version 535.129.03 and CUDA Toolkit to version 12.2.2
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/cuda_spec.rb
Labels: 3.x

#2567 [Dependencies] Upgrade NVIDIA driver to version 535.129.03 and CUDA Toolkit to version 12.2.2.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/cuda_spec.rb
Labels: 3.x

#2566 Disable installation of kernel-devel on Docker
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
Labels: skip-changelog-update, 3.x

#2560 [Dependencies] Upgrade GDRCopy to version 2.4.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/partial/_gdrcopy_common.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/partial/_gdrcopy_common_rhel.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: 3.x

#2568 [Dependencies] Upgrade GDRCopy to version 2.4.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_ubuntu20+.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/partial/_gdrcopy_common.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/partial/_gdrcopy_common_rhel.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: 3.x

#2572 [develop] - Fix GDRCopy installation on RHEL derivatives
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_rocky8.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: skip-changelog-update, 3.x

#2571 [release-3.8] - Fix GDRCopy installation on RHEL derivatives
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_rocky8.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: skip-changelog-update, 3.x

#2570 Add restart to service "supervisord"
  cookbooks/aws-parallelcluster-platform/recipes/finalize.rb
Labels: skip-changelog-update

#2578 [Dependencies] Fix to use GDRCopy v2.3.1 only in Centos7.
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/partial/_gdrcopy_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: skip-changelog-update

#2579 [Dependencies] Fix to use GDRCopy v2.3.1 only in Centos7.
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/gdrcopy_centos7.rb
  cookbooks/aws-parallelcluster-platform/resources/gdrcopy/partial/_gdrcopy_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: skip-changelog-update

#2582 [Release 3.8] Ensure the initial internal efs filesystem is not remou…
  cookbooks/aws-parallelcluster-environment/recipes/config/efs.rb
Labels: skip-changelog-update

#2581 [Develop] Ensure the initial internal efs filesystem is not remounted…
  cookbooks/aws-parallelcluster-environment/recipes/config/efs.rb
Labels: skip-changelog-update

#2585 [feature] Fix bugs in External Slurmdbd cookbook
  cookbooks/aws-parallelcluster-entrypoints/recipes/external_slurmdbd_config.rb
Labels: skip-changelog-update, 3.x
