Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-03, with the labels that each got.

#2668 Bump Version to 3.10.0
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: skip-changelog-update, 3.x

#2670 [DFSM][Docs] Add 3.9.0 changelog item about dynamic file system mounting without fleet replacement.
  CHANGELOG.md
Labels: 3.x, Documentation

#2669 [DFSM][Docs] Add 3.9.0 changelog item about dynamic file system mounting without fleet replacement.
  CHANGELOG.md
Labels: 3.x, Documentation

#2673 Get instances from DynamoDB in batches of 100
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_checks/common/constants.py
  test/unit/head_node_checks/test_check_cluster_ready.py
Labels: skip-changelog-update

#2674 [develop] Get instances from DynamoDB in batches of 100
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_checks/common/constants.py
  test/unit/head_node_checks/test_check_cluster_ready.py
Labels: skip-changelog-update

#2677 [release-3.9][DFSM]Using .login_nodes_keys_sync_file to be used during Init and Update phase of the clusters
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/recipes/config/login_nodes_keys.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/login_nodes_keys_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/helpers.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2678 [DFSM]Using .login_nodes_keys_sync_file to be used during Init and Update phase of the clusters
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/recipes/config/login_nodes_keys.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/login_nodes_keys_spec.rb
  cookbooks/aws-parallelcluster-shared/libraries/helpers.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2679 [Release 3.9][Dependencies] Update checksum for DCV
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu20.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu22.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_rhel_common.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2680 [Dependencies] Update DCV CheckSums for 2023.1-16388
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu20.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu22.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_rhel_common.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2681 [release-3.9][Dependencies] Update checksum for DCV on Ubuntu20
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu20.rb
Labels: skip-changelog-update, skip-system-tests

#2686 [release-3.9]Adding Minor changes for CHANGELOG.md
  CHANGELOG.md
Labels: skip-changelog-update, 3.x

#2687 [release-3.9]Rearrange the Changelog according to priority
  CHANGELOG.md
Labels: skip-changelog-update, 3.x

#2685 Update DCV checksum and changelog
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu20.rb
Labels: skip-changelog-update, 3.x

#2689 DCV: add explicit path for curl command
  cookbooks/aws-parallelcluster-platform/files/dcv/pcluster_dcv_connect.sh
Labels: skip-changelog-update
