Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-05, with the labels that each got.

#2718 Avoid /opt/intel when backing up, restoring, and mounting fs mount points on arm instances
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/backup_internal_use_shared_data.rb
Labels: skip-changelog-update

#2719 Add a log message describing the active processes using a mount point during unmounting
  cookbooks/aws-parallelcluster-entrypoints/recipes/finalize.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/init.rb
  cookbooks/aws-parallelcluster-entrypoints/recipes/update.rb
  cookbooks/aws-parallelcluster-entrypoints/spec/unit/recipes/finalize_spec.rb
  cookbooks/aws-parallelcluster-entrypoints/spec/unit/recipes/update_spec.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-environment/resources/file_utils.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/volume_spec.rb
Labels: skip-changelog-update

#2722 Avoid /opt/intel when backing up, restoring, and mounting fs mount points on arm instances (#2718)
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/backup_internal_use_shared_data.rb
Labels: skip-changelog-update

#2721 Avoid /opt/intel when backing up, restoring, and mounting fs mount points on arm instances
  cookbooks/aws-parallelcluster-computefleet/files/clusterstatusmgtd/clusterstatusmgtd.py
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/backup_internal_use_shared_data.rb
Labels: skip-changelog-update

#2724 [Test] Require 'ostruct' module in spec tests to prevent runtime errors cause by OpenStruct not being defined in newer version of Cinc.
  cookbooks/aws-parallelcluster-entrypoints/spec/unit/recipes/finalize_spec.rb
  cookbooks/aws-parallelcluster-entrypoints/spec/unit/recipes/update_spec.rb
Labels: skip-changelog-update, 3.x, Test

#2725 [Bugfix] Check processes using a given path only if the path exists.
  cookbooks/aws-parallelcluster-environment/resources/file_utils.rb
Labels: bug, skip-changelog-update, 3.x

#2726 [AL2023]Changing the syntax for the command as it gives error for a numercial error
  util/cinc-install.sh
Labels: skip-changelog-update, 3.x

#2713 Upgrade Cinc to version 18.4.12
  CHANGELOG.md
  kitchen.ec2.yml
Labels: 3.x

#2728 [Supervisord] Remove extra tab added for ADC regions only, compromisi…
  cookbooks/aws-parallelcluster-platform/templates/supervisord/parallelcluster_supervisord.conf.erb
Labels: skip-changelog-update, 3.x

#2730 Changing the PATH order we set for using the cfnbootstrap script we have installed in virtualenv rather than using default scripts
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/pcluster.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
Labels: skip-changelog-update, 3.x

#2733 Adding different values for `kernel-open` option
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
Labels: bug, skip-changelog-update, 3.x, skip-system-tests

#2734 [Bug] Adding different values for `kernel-open` option
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
Labels: bug, skip-changelog-update, 3.x, skip-system-tests

#2735 Bump version to 3.9.2
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: skip-changelog-update

#2739 Reverting the PATH for cfnbootstrap
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/pcluster.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
Labels: skip-changelog-update, 3.x

#2727 [Develop] Add data integrity checks before removing backup directories
  cookbooks/aws-parallelcluster-environment/recipes/init/config_default_user_home.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/restore_home_shared_data.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/restore_internal_use_shared_data.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/config_default_user_home_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/mount_internal_use_efs_spec.rb
Labels: skip-changelog-update, 3.x, skip-recursive-deletion-check

#2743 [Storage] Fix method used to get the AWS domain for FSx.
  cookbooks/aws-parallelcluster-environment/libraries/fsx.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/libraries/fsx_spec.rb
Labels: bug, skip-changelog-update, 3.x, Test
