Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-09, with the labels that each got.

#2798 Install and Use dos2unix package to convert custom action scripts before execution
  cookbooks/aws-parallelcluster-environment/files/custom_action_executor/custom_action_executor.py
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_alinux2023.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_redhat8.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu20.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_ubuntu22.rb
  test/unit/custom_action_executor/test_custom_action_executor.py
Labels: skip-changelog-update, skip-security-exclusions-check

#2799 Avoid using `sinfo -N` to support cluster creation with large compute nodes
  cookbooks/aws-parallelcluster-computefleet/recipes/config/fleet_status.rb
  cookbooks/aws-parallelcluster-computefleet/templates/compute_fleet_status/is_fleet_ready.erb
  cookbooks/aws-parallelcluster-slurm/libraries/helpers.rb
Labels: skip-changelog-update

#2805 Downgrade Slurm to 23.11.10
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: skip-changelog-update

#2806 Change enroot and pyxis urls to point to an s3 bucket
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/files/enroot/enroot.template.conf
  cookbooks/aws-parallelcluster-platform/resources/enroot/partial/_enroot_common.rb
  cookbooks/aws-parallelcluster-platform/resources/enroot/partial/_enroot_debian.rb
  cookbooks/aws-parallelcluster-platform/resources/enroot/partial/_enroot_rhel.rb
  cookbooks/aws-parallelcluster-platform/test/controls/enroot_spec.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pyxis.rb
Labels: skip-changelog-update

#2797 Prevent pcluster from changing default permissions on /home directory
  cookbooks/aws-parallelcluster-environment/recipes/config/mount_home.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/resources/manage_ebs.rb
  cookbooks/aws-parallelcluster-environment/resources/raid/partial/_raid_common.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
Labels: skip-changelog-update

#2808 [Dependencies] Fix Enroot+Caps URL used for RHEL.
  cookbooks/aws-parallelcluster-platform/resources/enroot/partial/_enroot_rhel.rb
Labels: skip-changelog-update, 3.x

#2807 Restarting cfn-hup if it hangs using supervisorctl
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/cfn-hup-runner.sh.erb
Labels: skip-changelog-update, 3.x

#2810 [Dependencies] Rename Enroot+Caps object URL from enroot+caps to enroot-caps to prevent URL encoding issues on RHEL and Debian.
  cookbooks/aws-parallelcluster-platform/resources/enroot/partial/_enroot_debian.rb
  cookbooks/aws-parallelcluster-platform/resources/enroot/partial/_enroot_rhel.rb
Labels: bug, skip-changelog-update, 3.x

#2811 Adding Attribution Document for Cookbook
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x, skip-system-tests
