Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-02, with the labels that each got.

#2633 Configure S3 mountpoint for external slurmdbd
  cookbooks/aws-parallelcluster-entrypoints/recipes/external_slurmdbd_config.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_external_slurmdbd_s3_mountpoint.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2635 Fetch slurmdbd configuration from S3 if available
  cookbooks/aws-parallelcluster-entrypoints/recipes/external_slurmdbd_config.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/retrieve_slurmdbd_config_from_s3.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2639 [DFSM] Add Python dependencies to cookbook virtual env: click and retrying.
  .isort.cfg
  cookbooks/aws-parallelcluster-platform/files/cookbook_virtualenv/requirements.txt
  test/unit/requirements.txt
Labels: skip-changelog-update, dependencies, 3.x

#2629 [DFSM] Make compute nodes update shared storage as part of the update workflow.
  cookbooks/aws-parallelcluster-environment/recipes/config/update_fs_mapping.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/update_fs_mapping_spec.rb
  cookbooks/aws-parallelcluster-platform/resources/fetch_config.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fetch_config_spec.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_compute.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/update_compute_spec.rb
Labels: skip-changelog-update, 3.x

#2638 Add recipe to disable not required services in ExternalSlurmdbd
  cookbooks/aws-parallelcluster-entrypoints/recipes/external_slurmdbd_config.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/external_slurmdbd_disable_unrequired_services.rb
Labels: skip-changelog-update, 3.x, skip-system-tests

#2636 [Dependencies] Enable Efa Version and Checksum to be overridden by ExtraChefAttributes
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/resources/efa/partial/_common.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
Labels: skip-changelog-update, 3.x

#2644 [DFSM] Make command that waits for cluster config version file OS independent.
  cookbooks/aws-parallelcluster-platform/resources/fetch_config.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fetch_config_spec.rb
Labels: bug, skip-changelog-update, 3.x

#2642 [develop] Fix network route tables configuration
  cookbooks/aws-parallelcluster-environment/recipes/config/network_interfaces.rb
Labels: skip-changelog-update

#2647 [DFSM] On cluster update, remove the check on static fleet and move the cluster readiness check before clustermgtd is restarted.
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/update_head_node_spec.rb
Labels: bug, skip-changelog-update, 3.x

#2648 [Dependencies] Pinning NVIDIA version for Centos7 to 535.129.03
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/nvidia_driver_centos7.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
Labels: skip-changelog-update, 3.x

#2646 [Disable Sudo] Invoking sudo_access from Platform cookbook when updating cluster
  cookbooks/aws-parallelcluster-entrypoints/recipes/update.rb
  cookbooks/aws-parallelcluster-platform/recipes/update.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/update_spec.rb
Labels: skip-changelog-update, 3.x

#2650 [Dependencies] Update PMIX to 4.2.9
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pmix.rb
Labels: skip-changelog-update, 3.x

#2651 [develop][Kitchen test] Fix AMI build failures on develop branch
  cookbooks/aws-parallelcluster-platform/test/controls/arm_pl_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/c_states_spec.rb
  cookbooks/aws-parallelcluster-shared/test/controls/package_repos_spec.rb
Labels: skip-changelog-update

#2622 [Dependencies] Upgrade NICE DCV to 2023.1-16388
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/attributes/platform.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu20.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/dcv_ubuntu22.rb
  cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_rhel_common.rb
Labels: 3.x

#2655 [BugFix] Fix issue making job fail when submitted as active directory user from login nodes.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-entrypoints/recipes/finalize.rb
  cookbooks/aws-parallelcluster-entrypoints/spec/spec_helper.rb
  cookbooks/aws-parallelcluster-entrypoints/spec/unit/recipes/finalize_spec.rb
  cookbooks/aws-parallelcluster-environment/recipes/config/directory_service.rb
  cookbooks/aws-parallelcluster-environment/recipes/finalize.rb
  cookbooks/aws-parallelcluster-environment/recipes/finalize/finalize_directory_service.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/finalize_directory_service_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/finalize_spec.rb
  cookbooks/aws-parallelcluster-shared/spec/spec_helper.rb
Labels: bug, 3.x

#2654 [kitchen tests] Fix pinning NVIDIA version for Centos7 to 535.129.03
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_spec.rb
Labels: skip-changelog-update

#2653 [unit tests] Support RHEL9 and Rocky9: fix missing changes
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/gdrcopy_spec.rb
Labels: skip-changelog-update

#2657 [Dependencies] Overriding the NVIDIA version for Centos7 using node_attributes
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_spec.rb
Labels: skip-changelog-update, 3.x

#2658 [DEX] Add possibility in 'upload-cookbook.sh' to specify an optional scope
  util/upload-cookbook.sh
Labels: skip-changelog-update, 3.x, Developer Experience

#2659 [AD] Fix the sync of AD data by moving the sync step at the end of the finalize phase with more retries.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-entrypoints/recipes/finalize.rb
  cookbooks/aws-parallelcluster-environment/recipes/finalize/finalize_directory_service.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/finalize_directory_service_spec.rb
Labels: bug, skip-changelog-update, 3.x

#2660 [DFSM] Increase the frequency of cfn-hup loop.
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/cfn-hup-runner.sh.erb
Labels: skip-changelog-update, 3.x

#2663 [DFSM] Fix method that determines if a live update is required.
  cookbooks/aws-parallelcluster-slurm/libraries/update.rb
Labels: bug, skip-changelog-update, 3.x

#2666 [Test] Cover the 'aws-parallelcluster-entrypoints:finalize' recipe with spec tests.
  cookbooks/aws-parallelcluster-entrypoints/spec/unit/recipes/finalize_spec.rb
Labels: skip-changelog-update, 3.x, Test

#2665 [3.x] Slurm Upgrade to 23.11.4
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: 3.x
