Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-06, with the labels that each got.

#2744 [github system test] Fix system test on Rocky 8
  kitchen.docker.yml
Labels: skip-changelog-update

#2740 Installing packages from BaseOS and AppStream if available
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
Labels: skip-changelog-update, 3.x

#2742 Renaming pcluster.sh profile to cookbook_environment.sh profile
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/cfn-hook-update.conf.erb
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/pcluster.sh.erb
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/pcluster_cookbook_environment.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
Labels: skip-changelog-update, 3.x

#2751 [Docs] Fix changelog entry for version 3.9.3.
  CHANGELOG.md
Labels: 3.x, Documentation

#2752 [Docs] Add changelog entry for 3.9.3 and 3.9.2
  CHANGELOG.md
Labels: 3.x, Documentation

#2756 [Docs] Add changelog entry for 3.9.3: cloud_dns.
  CHANGELOG.md
Labels: 3.x, Documentation

#2758 Adding the CFN_BOOTSTRAP_VIRTUALENV_PATH variable in cfn-hook-update.conf
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/cfn-hook-update.conf.erb
Labels: skip-changelog-update, 3.x

#2760 Using correct path of the profile created with CFN_BOOTSTRAP_VIRTUALENV_PATH
  cookbooks/aws-parallelcluster-environment/templates/cfn_bootstrap/cfn-hook-update.conf.erb
Labels: skip-changelog-update, 3.x

#2759 Remove `cloud_dns` from the `SlurmctldParameters` to avoid the slurm …
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
Labels: skip-changelog-update

#2748 [develop] Add logic to assert that the output of the diff command must do not contain lines starting with "Only in /tmp/home"
  cookbooks/aws-parallelcluster-environment/recipes/init/config_default_user_home.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/restore_home_shared_data.rb
  cookbooks/aws-parallelcluster-environment/recipes/init/restore_internal_use_shared_data.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/config_default_user_home_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/mount_internal_use_efs_spec.rb
Labels: skip-changelog-update, 3.x, skip-recursive-deletion-check

#2763 [AL2023] Configure NFS server the same way as AL2
  cookbooks/aws-parallelcluster-environment/resources/nfs/nfs_alinux2023.rb
Labels: skip-changelog-update

#2765 Fix Lustre not installed on RHEL 8.10
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/lustre_rocky8.rb
Labels: skip-changelog-update

#2766 Configure multi-nics on Amazon Linux 2023
  cookbooks/aws-parallelcluster-environment/files/amazon-2023/network_interfaces/configure_nw_interface.sh
  cookbooks/aws-parallelcluster-environment/recipes/config/network_interfaces.rb
  cookbooks/aws-parallelcluster-environment/resources/network_service/network_service_alinux2023.rb
  cookbooks/aws-parallelcluster-slurm/recipes/init/init_dns.rb
Labels: skip-changelog-update

#2768 Bump version to 3.11.0
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: skip-changelog-update
