Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-10, with the labels that each got.

#2818 [Documentation] Add changelog entry for version 3.11.1.
  CHANGELOG.md
Labels: 3.x, Documentation

#2819 [Documentation] Add changelog entry for version 3.11.1.
  CHANGELOG.md
Labels: 3.x, Documentation

#2821 [Documentation] Fix changelog entries for version 3.11.1.
  CHANGELOG.md
Labels: 3.x, Documentation

#2822 [Documentation] Fix changelog entries for version 3.11.1.
  CHANGELOG.md
Labels: 3.x, Documentation

#2824 [CodeStyle] Address Shellcheck finding 'SC2155 in iso-ca-bundle-config.sh'
  cookbooks/aws-parallelcluster-platform/files/isolated/iso-ca-bundle-config.sh
Labels: enhancement, skip-changelog-update, 3.x

#2825 [CodeStyle] Address Shellcheck finding 'SC2155 in iso-ca-bundle-config.sh'
  cookbooks/aws-parallelcluster-platform/files/isolated/iso-ca-bundle-config.sh
Labels: enhancement, skip-changelog-update, 3.x

#2815 [ADC] Configure certificates
  cookbooks/aws-parallelcluster-awsbatch/recipes/install.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/install/custom_parallelcluster_node.rb
  cookbooks/aws-parallelcluster-computefleet/recipes/install/parallelcluster_node.rb
  cookbooks/aws-parallelcluster-environment/resources/cloudwatch/partial/_cloudwatch_common.rb
  cookbooks/aws-parallelcluster-platform/files/isolated/iso-ca-bundle-config.sh
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_redhat8.rb
  cookbooks/aws-parallelcluster-shared/attributes/environment.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/fleet_status_manager_program.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/resume_program.erb
Labels: skip-changelog-update

#2829 [Test] Fix kitchen test: `install_pyxis_installed`
  cookbooks/aws-parallelcluster-slurm/test/controls/pyxis_spec.rb
Labels: bug, skip-changelog-update, 3.x, Test

#2828 [Test] Fix kitchen test: `install_pyxis_installed`
  cookbooks/aws-parallelcluster-slurm/test/controls/pyxis_spec.rb
Labels: bug, skip-changelog-update, 3.x, Test

#2831 [Test] Fix kitchen test related to enroot
  cookbooks/aws-parallelcluster-platform/test/controls/enroot_spec.rb
Labels: skip-changelog-update, 3.x, Test

#2832 [Test] Fix kitchen test related to enroot
  cookbooks/aws-parallelcluster-platform/test/controls/enroot_spec.rb
Labels: bug, skip-changelog-update, 3.x, Test

#2833 Add possibility to skip Lustre installation
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/libraries/fsx.rb
  cookbooks/aws-parallelcluster-environment/recipes/install.rb
Labels: skip-changelog-update
