Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2024-04, with the labels that each got.

#2693 [Versioning] Bump version to 3.9.1.
  cookbooks/aws-parallelcluster-awsbatch/metadata.rb
  cookbooks/aws-parallelcluster-computefleet/metadata.rb
  cookbooks/aws-parallelcluster-entrypoints/metadata.rb
  cookbooks/aws-parallelcluster-environment/metadata.rb
  cookbooks/aws-parallelcluster-platform/metadata.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
  cookbooks/aws-parallelcluster-shared/metadata.rb
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-tests/metadata.rb
  kitchen.ec2.yml
  metadata.rb
Labels: skip-changelog-update, 3.x

#2695 [Storage] Execute deletion of shared storage mount dir after lazy unmounting without recursion and only if the directory is empty.
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/volume_spec.rb
Labels: bug, skip-changelog-update, 3.x

#2694 [Versioning] Add CHANGELOG entries for version 3.9.1.
  CHANGELOG.md
Labels: 3.x

#2696 [Storage] Execute deletion of shared storage mount dir after lazy unm…
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/volume_spec.rb
Labels: skip-changelog-update, 3.x

#2697 [Versioning] Add CHANGELOG entries for version 3.9.1.
  CHANGELOG.md
Labels: 3.x

#2698 [Docs] Fix changelog entries for 3.9.1.
  CHANGELOG.md
Labels: 3.x

#2699 [Storage] Delete the shared directory only if the directory exists and it is empty.
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/volume_spec.rb
Labels: bug, skip-changelog-update, 3.x

#2707 [Storage] Delete the shared directory only if the directory exists and it is empty.
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_mount_umount.rb
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_mount_unmount.rb
  cookbooks/aws-parallelcluster-environment/resources/volume.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/lustre_mount_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/volume_spec.rb
Labels: skip-changelog-update, 3.x

#2710 [Slurm] Make slurmctld and slurmdbd services wait for remote file systems to be mounted before being started.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/slurmctld.service.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/slurmdbd.service.erb
Labels: enhancement, 3.x

#2712 Upgrading cinc-install script to use latest version
  util/cinc-install.sh
Labels: skip-changelog-update, 3.x

#2714 Simplify conditional statements in slurm conf template
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/templates/slurm_parallelcluster.conf
Labels: skip-changelog-update

#2715 [kitchen tests] Remove checksum checks of CloudWatch source code files
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update

#2716 Upload more logs to CloudWatch from login node and external dbd node
  cookbooks/aws-parallelcluster-environment/files/cloudwatch/cloudwatch_agent_config.json
Labels: skip-changelog-update

#2717 Add possibility to disable slurmdbd systemd service and extend timeout
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_slurm_accounting.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/config_slurm_accounting_spec.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/head_node/slurmdbd.service.erb
Labels: skip-changelog-update
