Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2025-03, with the labels that each got.

#2892 [Dependencies] Upgrade EFA installer to version 1.38.0 (from 1.36.0).
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
Labels: dependencies, 3.x

#2895 Download http-parser from s3
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/isolated_install_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/isolated/patch-iso-instance.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/isolated_spec.rb
  cookbooks/aws-parallelcluster-platform/files/isolated/iso-ca-bundle-config.sh
  cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_alinux2023.rb
Labels: skip-changelog-update

#2894 [ActiveDirectory] Fix usage of authselect which used to cause node boostrap failures on Rocky 9.5+ when directory service is used.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/resources/system_authentication/system_authentication_rocky8.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/system_authentication_spec.rb
Labels: bug, 3.x

#2897 Using classic domain for installing aws cli in china
  cookbooks/aws-parallelcluster-platform/recipes/install/awscli.rb
Labels: skip-changelog-update, 3.x

#2901 [Docs] Update changelog for release 3.13.0.
  CHANGELOG.md
Labels: 3.x, Documentation

#2906 [EFA] Upgrade EFA to version 1.38.1 (from 1.38.0) to address issue on Rocky9.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
Labels: dependencies, 3.x

#2908 Update the default root volume size to 45 GB
  kitchen.ec2.yml
Labels: skip-changelog-update

#2911 Use separate commands when copying files and preserving permissions
  cookbooks/aws-parallelcluster-platform/recipes/config/cluster_user.rb
Labels: skip-changelog-update

#2905 Shortening RHEL/Rock boot time by deprioritizing ipv6 and disable internet check
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/files/redhat/dns_domain/99-disable-ipv6-metadata.cfg
  cookbooks/aws-parallelcluster-slurm/files/redhat/dns_domain/NetworkManager.conf
  cookbooks/aws-parallelcluster-slurm/files/rocky/dns_domain/99-disable-ipv6-metadata.cfg
  cookbooks/aws-parallelcluster-slurm/files/rocky/dns_domain/NetworkManager.conf
  cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_redhat8.rb
  cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_rocky8.rb
Labels: skip-changelog-update

#2912 Install Lustre client for Ubuntu24
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_install_lustre_debian.rb
  cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb
Labels: 3.x, skip-system-tests

#2915 Adding Ubuntu24 for kitchen tests for storage
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/sticky_bits_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/mysql_client_spec.rb
  test/environments/kitchen.rb
Labels: skip-changelog-update, 3.x

#2916 [Kitchen test] Add Ubuntu Os for C_state Install phase tests
  cookbooks/aws-parallelcluster-platform/test/controls/c_states_spec.rb
Labels: skip-changelog-update, 3.x

#2918 [Kitchen Test] Use os_properties outside it block
  cookbooks/aws-parallelcluster-environment/test/controls/cloudwatch_spec.rb
Labels: skip-changelog-update, 3.x

#2919 Clean resolv.conf at the end of AMI build
  cookbooks/aws-parallelcluster-platform/files/ami_cleanup.sh
Labels: skip-changelog-update

#2920 Clean Resolv.conf in official AMI build
  cookbooks/aws-parallelcluster-platform/files/ami_cleanup.sh
Labels: skip-changelog-update

#2923 [Rhel + Rocky] Remove route mertic from NetworkManager
  cookbooks/aws-parallelcluster-slurm/files/redhat/dns_domain/NetworkManager.conf
  cookbooks/aws-parallelcluster-slurm/files/rocky/dns_domain/NetworkManager.conf
Labels: skip-changelog-update, 3.x

#2924 Consider string "true" as turning on Lustre, Nvidia installation
  cookbooks/aws-parallelcluster-environment/libraries/fsx.rb
  cookbooks/aws-parallelcluster-platform/libraries/nvidia.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_common.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_dcgm/partial/_nvidia_dcgm_common.rb
  cookbooks/aws-parallelcluster-platform/test/controls/enroot_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_dcgm_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/pyxis_spec.rb
Labels: skip-changelog-update
