Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2025-05, with the labels that each got.

#2937 [Docs] Add changelog for version 3.13.1.
  CHANGELOG.md
Labels: 3.x, Documentation

#2934 [Dependencies] Upgrade SLURM to version 24.05.8 (from 24.05.7).
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: dependencies, 3.x

#2940 Fix Github check by pinning the docker image
  kitchen.docker.yml
Labels: skip-changelog-update

#2939 Fix Github check by pinning the docker image
  kitchen.docker.yml
Labels: skip-changelog-update

#2936 Relax inspec test for cstate to accept "no idle states"
  cookbooks/aws-parallelcluster-platform/test/controls/c_states_spec.rb
Labels: skip-changelog-update

#2944 Update the efs-utils to use a different Cargo.toml
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/files/efs/Cargo.toml
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_debian.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_install_from_tar.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_redhat_based.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efs_spec.rb
Labels: 3.x

#2945 [Bug] Installing Pyxis if nvidia is installed
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pyxis.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/install_pyxis_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/pyxis_spec.rb
Labels: skip-changelog-update, 3.x

#2943 [ARMPL] Fix a bug in the installation of GCC required by ARM Performance Library to cover both gcc 9.3 and gcc 11.3. In particular gcc 9.3.0 requires ftp endpoint, whereas gcc 11.3.0 requires http endpoint.
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/partial/_arm_pl_common.rb
Labels: skip-changelog-update, 3.x

#2947 [ARMPL] Fetch gcc deps from public bucket
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/partial/_arm_pl_common.rb
Labels: skip-changelog-update, dependencies, 3.x

#2946 [Bug] Installing Pyxis if nvidia is installed
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pyxis.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/install_pyxis_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/pyxis_spec.rb
Labels: skip-changelog-update, 3.x

#2954 [Doc] fix changelog about efa upgrade.
  CHANGELOG.md
Labels: Documentation

#2956 [test] Reeenable install_munge_folders_created check
  cookbooks/aws-parallelcluster-slurm/test/controls/munge_spec.rb
Labels: skip-changelog-update

#2955 [Bug] Installing Pyxis if nvidia is installed or enabled
  cookbooks/aws-parallelcluster-slurm/recipes/install/install_pyxis.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/recipes/install_pyxis_spec.rb
  cookbooks/aws-parallelcluster-slurm/test/controls/pyxis_spec.rb
Labels: skip-changelog-update, 3.x

#2938 [Dependencies] Upgrade SLURM to version 24.05.8 (from 24.05.7).
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: skip-changelog-update, dependencies, 3.x

#2959 [release-3.13] Give `systemctl poweroff --force` the sudoer permission
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/99-parallelcluster-slurm.erb
Labels: skip-changelog-update, 3.x
