Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2025-06, with the labels that each got.

#2969 [3.13.1] Fix changelog
  CHANGELOG.md
Labels: 3.x

#2967 Install kernel-modules-extra with matching version of the running kernel
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/nvidia_driver_alinux2023.rb
Labels: skip-changelog-update

#2976 [Docs] Add changelog for version 3.13.2
  CHANGELOG.md
Labels: Documentation

#2977 Improve build-image on non-latest Rocky
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-config.yml
  cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml
  cookbooks/aws-parallelcluster-platform/resources/install_packages/install_packages_rocky8.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_common.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_debian.rb
  cookbooks/aws-parallelcluster-platform/resources/install_packages/partial/_install_packages_rhel_amazon.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/nvidia_driver_alinux2023.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/install_packages_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/install_packages_spec.rb
Labels: skip-changelog-update

#2979 [Docs] Revise changelog for version 3.13.2
  CHANGELOG.md
Labels: Documentation

#2981 [Docs] Revise changelog for version 3.13.2
  CHANGELOG.md
Labels: Documentation

#2985 Fix kitchen tests after change to install enroot when nvidia is installed
  cookbooks/aws-parallelcluster-platform/test/controls/enroot_spec.rb
Labels: skip-changelog-update
