Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2025-08, with the labels that each got.

#3004 Avoid Python re-installation if already installed
  cookbooks/aws-parallelcluster-shared/resources/install_pyenv.rb
Labels: skip-changelog-update

#3002 [SlurmTopo] Add support for slurm Block Topology
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_topology_generator.py
  cookbooks/aws-parallelcluster-slurm/recipes/config/config_head_node.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/block_topology_alinux2023.rb
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/block_topology_amazon2.rb
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/block_topology_redhat8.rb
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/block_topology_rocky8.rb
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/block_topology_ubuntu22+.rb
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/partial/_block_topology_common.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/resources/block_topology_spec.rb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/block_topology/slurm_parallelcluster_topology.conf.erb
  cookbooks/aws-parallelcluster-slurm/templates/default/slurm/slurm.conf.erb
  test/unit/slurm/test_topology_generator.py
  test/unit/slurm/test_topology_generator/test_generate_topology_config/expected_outputs/topology_with_capacity_block.conf
  test/unit/slurm/test_topology_generator/test_generate_topology_config/sample_no_capacity_block.yaml
  test/unit/slurm/test_topology_generator/test_generate_topology_config/sample_with_capacity_block.yaml
Labels: skip-changelog-update, 3.x

#3008 [SlurmTopo] Use `--force-configuration` option for creating topology configuration
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
  cookbooks/aws-parallelcluster-slurm/files/default/head_node_slurm/slurm/pcluster_topology_generator.py
  cookbooks/aws-parallelcluster-slurm/resources/block_topology/partial/_block_topology_common.rb
  cookbooks/aws-parallelcluster-slurm/spec/unit/resources/block_topology_spec.rb
  test/unit/slurm/test_topology_generator.py
  test/unit/slurm/test_topology_generator/test_generate_topology_config/expected_outputs/topology_with_capacity_block_force.conf
  test/unit/slurm/test_topology_generator/test_generate_topology_config/sample_with_capacity_block.yaml
Labels: skip-changelog-update, 3.x

#3012 [EFA] Upgrade EFA to 1.43.2
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/attributes/environment.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/efa_spec.rb
Labels: 3.x

#3014 [Fabric] Install NVIDIA Fabric manager for ARM instances
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_fabric_manager_spec.rb
Labels: 3.x

#3011 [Isolated] Update Pypi dependencies and install efs-proxy dependency
  cookbooks/aws-parallelcluster-computefleet/recipes/install/custom_parallelcluster_node.rb
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/efs_redhat8.rb
  cookbooks/aws-parallelcluster-environment/resources/efs/partial/_install_from_tar.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cookbook_virtualenv.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/cookbook_virtualenv_spec.rb
  util/upload-cookbook.sh
Labels: skip-changelog-update

#3015 [Gb200]Skip Fabric Manager installation on Gb200 instance
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/libraries/nvidia.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/fabric_manager_amazon2.rb
  cookbooks/aws-parallelcluster-platform/resources/fabric_manager/partial/_fabric_manager_common.rb
  cookbooks/aws-parallelcluster-platform/resources/nvidia_imex/partial/_nvidia_imex_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fabric_manager_spec.rb
  cookbooks/aws-parallelcluster-platform/test/controls/nvidia_fabric_manager_spec.rb
Labels: skip-changelog-update, 3.x
