Repository aws/aws-parallelcluster-cookbook, pull requests merged in 2025-02, with the labels that each got.

#2870 [Dependencies] Upgrade PMIX to 5.0.6
  CHANGELOG.md
  cookbooks/aws-parallelcluster-slurm/attributes/slurm_attributes.rb
Labels: 3.x

#2871 [Dependencies] Upgrade ARMPL to 24.10
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/resources/arm_pl/partial/_arm_pl_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/arm_pl_spec.rb
  cookbooks/aws-parallelcluster-platform/templates/arm_pl/armpl_modulefile.erb
  cookbooks/aws-parallelcluster-platform/test/controls/arm_pl_spec.rb
Labels: 3.x

#2872 Download http-parser from s3
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/isolated_install_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/isolated/patch-iso-instance.sh.erb
  cookbooks/aws-parallelcluster-environment/test/controls/isolated_spec.rb
  cookbooks/aws-parallelcluster-platform/files/isolated/iso-ca-bundle-config.sh
  cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_alinux2023.rb
Labels: skip-changelog-update

#2873 Remove creation of SSH keys of type DSA to prevent cluster creation failure when the OS ships a version of OpenSSH that does not support DSA keys.
  CHANGELOG.md
  cookbooks/aws-parallelcluster-environment/files/login_nodes/keys-manager.sh
  cookbooks/aws-parallelcluster-environment/test/controls/login_nodes_keys_spec.rb
Labels: bug, 3.x, Security

#2874 Revert "Downgrade Slurm to 23.11.10"
  cookbooks/aws-parallelcluster-slurm/attributes/versions.rb
Labels: skip-changelog-update

#2877 [Doc] Update attribution document.
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x, Documentation, skip-bad-url-suffix-check

#2868 [IMDS Lockdown] Add example of usage to imds-access.sh helper.
  cookbooks/aws-parallelcluster-environment/files/imds/imds-access.sh
Labels: skip-changelog-update, 3.x

#2879 [Docs] Update attribution document with fixed dependencies and accessible links to tarball.
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x, Documentation, skip-bad-url-suffix-check

#2878 [Nvidia] Remove 'no-cc-version-check' from installation of nvidia driver
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/nvidia_driver_spec.rb
Labels: 3.x

#2875 [Scaling] Remove usage of cfn-init in Compute Fleet
  cookbooks/aws-parallelcluster-environment/files/cfn_hup_configuration/share_compute_fleet_dna.py
  cookbooks/aws-parallelcluster-environment/kitchen.environment-config.yml
  cookbooks/aws-parallelcluster-environment/recipes/config.rb
  cookbooks/aws-parallelcluster-environment/recipes/config/config_cfn_hup.rb
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/resources/cfn_hup_configuration.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/config_cfn_hup_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/config_spec.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/resources/cfn_hup_configuration_spec.rb
  cookbooks/aws-parallelcluster-environment/templates/cfn_hup_configuration/ComputeFleet/cfn-hup-update-action.sh.erb
  cookbooks/aws-parallelcluster-environment/templates/cfn_hup_configuration/cfn-hook-update.conf.erb
  cookbooks/aws-parallelcluster-environment/templates/cfn_hup_configuration/cfn-hup-runner.sh.erb
  cookbooks/aws-parallelcluster-environment/templates/cfn_hup_configuration/cfn-hup.conf.erb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_hup_configuration_spec.rb
  cookbooks/aws-parallelcluster-platform/recipes/update.rb
  cookbooks/aws-parallelcluster-platform/resources/fetch_dna_files.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/resources/fetch_dna_files_spec.rb
  cookbooks/aws-parallelcluster-slurm/Berksfile
  cookbooks/aws-parallelcluster-slurm/metadata.rb
  cookbooks/aws-parallelcluster-slurm/recipes/update/update_head_node.rb
  pytest.ini
  test/unit/cfn_hup_configuration/test_share_compute_fleet_dna.py
  test/unit/cfn_hup_configuration/test_share_compute_fleet_dna/test_get_write_directives_section/user_data_1.txt
  test/unit/cfn_hup_configuration/test_share_compute_fleet_dna/test_get_write_directives_section/user_data_2.txt
  tox.ini
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check, skip-recursive-deletion-check

#2882 [Scaling] Update changelog
  CHANGELOG.md
Labels: 3.x

#2881 Do not install lustre on ubuntu2404
  cookbooks/aws-parallelcluster-environment/resources/lustre/partial/_install_lustre_debian.rb
  cookbooks/aws-parallelcluster-platform/test/controls/install_packages_spec.rb
Labels: skip-changelog-update

#2884 [Scaling] Add logs in share_compute_fleet_dna.py
  cookbooks/aws-parallelcluster-environment/files/cfn_hup_configuration/share_compute_fleet_dna.py
  cookbooks/aws-parallelcluster-environment/resources/cfn_hup_configuration.rb
Labels: skip-changelog-update, 3.x

#2885 [Test] Fix Python version in kitchen tests related to AWS Batch and CFN Boostrap scripts. In particular, we expect all Oses to use Python 3.12.8, except for AL2 which uses 3.9.20.
  cookbooks/aws-parallelcluster-awsbatch/test/controls/awsbatch_virtualenv_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
Labels: skip-changelog-update, 3.x, Test

#2886 Revert "Upgrade python version to 3.12 for all OSs except AL2"
  CHANGELOG.md
  cookbooks/aws-parallelcluster-awsbatch/recipes/awsbatch_virtualenv.rb
  cookbooks/aws-parallelcluster-awsbatch/test/controls/awsbatch_virtualenv_spec.rb
  cookbooks/aws-parallelcluster-computefleet/kitchen.computefleet-config.yml
  cookbooks/aws-parallelcluster-computefleet/recipes/install/custom_parallelcluster_node.rb
  cookbooks/aws-parallelcluster-environment/recipes/install/cfn_bootstrap.rb
  cookbooks/aws-parallelcluster-environment/spec/unit/recipes/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-environment/test/controls/cfn_bootstrap_spec.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/awscli.rb
  cookbooks/aws-parallelcluster-platform/recipes/install/cookbook_virtualenv.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/awscli_spec.rb
  cookbooks/aws-parallelcluster-shared/attributes/versions.rb
Labels: 3.x

#2883 Use disable_services.rb recipe to disable dynamically provided services
  CHANGELOG.md
  cookbooks/aws-parallelcluster-platform/recipes/install/disable_services.rb
  cookbooks/aws-parallelcluster-platform/spec/unit/recipes/disable_services_spec.rb
Labels: 3.x

#2890 Allow overriding of node package only on HeadNode during an Update
  CHANGELOG.md
  cookbooks/aws-parallelcluster-computefleet/recipes/config/update_parallelcluster_node.rb
Labels: 3.x
